package uk.gov.hmcts.probate.model.exceptionrecord;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

@Builder
@Data
@AllArgsConstructor
public class ExceptionRecordOCRFields {

    // Caveats
    private String caveatorForenames;
    private String caveatorSurnames;
    private final String caveatorEmailAddress;
    private String caveatorAddressLine1;
    private final String caveatorAddressLine2;
    private final String caveatorAddressTown;
    private final String caveatorAddressCounty;
    private String caveatorAddressPostCode;
    private String solsSolicitorRepresentativeName;
    private final String dxNumber;
    private final String practitionerAcceptsServiceByEmail;
    private String solsSolicitorFirmName;
    private String solsSolicitorAppReference;
    private String solsSolicitorAddressLine1;
    private String solsSolicitorAddressLine2;
    private String solsSolicitorAddressTown;
    private final String solsSolicitorAddressCounty;
    private String solsSolicitorAddressPostCode;
    private String solsSolicitorEmail;
    private String solsSolicitorPhoneNumber;
    private String deceasedForenames;
    private String deceasedSurname;
    private String deceasedDateOfDeath;
    private String deceasedDateOfBirth;
    private String deceasedAnyOtherNames;
    private String deceasedAddressLine1;
    private final String deceasedAddressLine2;
    private final String deceasedAddressTown;
    private final String deceasedAddressCounty;
    private String deceasedAddressPostCode;
    private final String caseReference;
    //new form PA8A
    private final String caveatorPhoneNumber;
    private final String probateFee;
    private final String probateFeeNotIncludedReason;
    private final String helpWithFeesReference;
    private final String probateFeeNotIncludedExplanation;
    private final String probateFeeAccountNumber;
    private final String probateFeeAccountReference;
    private final String bilingualCorrespondenceRequested;
    private final String legalRepresentative;

    // PA1A and PA1P
    private final String extraCopiesOfGrant;
    private final String outsideUKGrantCopies;
    private final String applicationFeePaperForm;
    private final String feeForCopiesPaperForm;
    private final String totalFeePaperForm;
    private final String paperPaymentMethod;
    private final String solsFeeAccountNumber;
    private final String paymentReferenceNumberPaperform;
    private String primaryApplicantForenames;
    private String primaryApplicantSurname;
    private String primaryApplicantHasAlias;
    private String primaryApplicantAlias;
    private String primaryApplicantAddressLine1;
    private final String primaryApplicantAddressLine2;
    private final String primaryApplicantAddressTown;
    private final String primaryApplicantAddressCounty;
    private String primaryApplicantAddressPostCode;
    private final String primaryApplicantPhoneNumber;
    private final String primaryApplicantSecondPhoneNumber;
    private final String primaryApplicantEmailAddress;
    private final String executorsApplying0applyingExecutorName;
    private String executorsApplying0applyingExecutorAddressLine1;
    private final String executorsApplying0applyingExecutorAddressLine2;
    private String executorsApplying0applyingExecutorAddressTown;
    private final String executorsApplying0applyingExecutorAddressCounty;
    private String executorsApplying0applyingExecutorAddressPostCode;
    private final String executorsApplying0applyingExecutorEmail;
    private final String executorsApplying0applyingExecutorDifferentNameToWill;
    private String executorsApplying0applyingExecutorOtherNames;
    private final String executorsApplying1applyingExecutorName;
    private String executorsApplying1applyingExecutorAddressLine1;
    private final String executorsApplying1applyingExecutorAddressLine2;
    private String executorsApplying1applyingExecutorAddressTown;
    private final String executorsApplying1applyingExecutorAddressCounty;
    private String executorsApplying1applyingExecutorAddressPostCode;
    private final String executorsApplying1applyingExecutorEmail;
    private final String executorsApplying1applyingExecutorDifferentNameToWill;
    private String executorsApplying1applyingExecutorOtherNames;
    private final String executorsApplying2applyingExecutorName;
    private String executorsApplying2applyingExecutorAddressLine1;
    private final String executorsApplying2applyingExecutorAddressLine2;
    private String executorsApplying2applyingExecutorAddressTown;
    private final String executorsApplying2applyingExecutorAddressCounty;
    private String executorsApplying2applyingExecutorAddressPostCode;
    private final String executorsApplying2applyingExecutorEmail;
    private final String executorsApplying2applyingExecutorDifferentNameToWill;
    private String executorsApplying2applyingExecutorOtherNames;
    private String solsSolicitorIsApplying;
    private String deceasedDomicileInEngWales;
    private final String deceasedMartialStatus;
    private final String dateOfMarriageOrCP;
    private final String dateOfDivorcedCPJudicially;
    private final String courtOfDecree;
    private final String foreignAsset;
    private final String foreignAssetEstateValue;
    private final String adopted;
    private final String adoptiveRelatives0name;
    private final String adoptiveRelatives0relationship;
    private final String adoptiveRelatives0adoptedInOrOut;
    private final String adoptiveRelatives1name;
    private final String adoptiveRelatives1relationship;
    private final String adoptiveRelatives1adoptedInOrOut;
    private final String adoptiveRelatives2name;
    private final String adoptiveRelatives2relationship;
    private final String adoptiveRelatives2adoptedInOrOut;
    private final String adoptiveRelatives3name;
    private final String adoptiveRelatives3relationship;
    private final String adoptiveRelatives3adoptedInOrOut;
    private final String adoptiveRelatives4name;
    private final String adoptiveRelatives4relationship;
    private final String adoptiveRelatives4adoptedInOrOut;
    private final String adoptiveRelatives5name;
    private final String adoptiveRelatives5relationship;
    private final String adoptiveRelatives5adoptedInOrOut;
    private final String solsWillType;
    private final String solsWillTypeReason;
    private final String bilingualGrantRequested;
    private String spouseOrPartner;
    private final String childrenUnderEighteenSurvived;
    private final String childrenOverEighteenSurvived;
    private final String childrenDiedUnderEighteen;
    private final String childrenDiedOverEighteen;
    private final String grandChildrenSurvivedUnderEighteen;
    private final String grandChildrenSurvivedOverEighteen;
    private final String parentsExistUnderEighteenSurvived;
    private final String parentsExistOverEighteenSurvived;
    private final String wholeBloodSiblingsSurvivedUnderEighteen;
    private final String wholeBloodSiblingsSurvivedOverEighteen;
    private final String wholeBloodSiblingsDiedUnderEighteen;
    private final String wholeBloodSiblingsDiedOverEighteen;
    private final String wholeBloodNeicesAndNephewsUnderEighteen;
    private final String wholeBloodNeicesAndNephewsOverEighteen;
    private final String halfBloodSiblingsSurvivedUnderEighteen;
    private final String halfBloodSiblingsSurvivedOverEighteen;
    private final String halfBloodSiblingsDiedUnderEighteen;
    private final String halfBloodSiblingsDiedOverEighteen;
    private final String halfBloodNeicesAndNephewsUnderEighteen;
    private final String halfBloodNeicesAndNephewsOverEighteen;
    private final String grandparentsDiedUnderEighteen;
    private final String grandparentsDiedOverEighteen;
    private final String wholeBloodUnclesAndAuntsSurvivedUnderEighteen;
    private final String wholeBloodUnclesAndAuntsSurvivedOverEighteen;
    private final String wholeBloodUnclesAndAuntsDiedUnderEighteen;
    private final String wholeBloodUnclesAndAuntsDiedOverEighteen;
    private final String wholeBloodCousinsSurvivedUnderEighteen;
    private final String wholeBloodCousinsSurvivedOverEighteen;
    private final String halfBloodUnclesAndAuntsSurvivedUnderEighteen;
    private final String halfBloodUnclesAndAuntsSurvivedOverEighteen;
    private final String halfBloodUnclesAndAuntsDiedUnderEighteen;
    private final String halfBloodUnclesAndAuntsDiedOverEighteen;
    private final String halfBloodCousinsSurvivedUnderEighteen;
    private final String halfBloodCousinsSurvivedOverEighteen;
    private final String primaryApplicantRelationshipToDeceased;
    private final String secondApplicantRelationshipToDeceased;
    private final String thirdApplicantRelationshipToDeceased;
    private final String fourthApplicantRelationshipToDeceased;
    private final String applyingAsAnAttorney;
    private final String attorneyOnBehalfOfName;
    private final String attorneyOnBehalfOfAddressLine1;
    private final String attorneyOnBehalfOfAddressLine2;
    private final String attorneyOnBehalfOfAddressTown;
    private final String attorneyOnBehalfOfAddressCounty;
    private final String attorneyOnBehalfOfAddressPostCode;
    private final String mentalCapacity;
    private final String courtOfProtection;
    private final String epaOrLpa;
    private final String epaRegistered;
    private final String domicilityCountry;
    private final String domicilityEntrustingDocument;
    private final String domicilitySuccessionIHTCert;
    private final String willDate;
    private final String willHasCodicils;
    private final String willsOutsideOfUK;
    private final String deceasedMarriedAfterWillOrCodicilDate;
    private final String willGiftUnderEighteen;
    private final String executorsNotApplying0notApplyingExecutorName;
    private String executorsNotApplying0notApplyingExecutorReason;
    private final String executorsNotApplying1notApplyingExecutorName;
    private String executorsNotApplying1notApplyingExecutorReason;
    private final String executorsNotApplying2notApplyingExecutorName;
    private String executorsNotApplying2notApplyingExecutorReason;
    private String notifiedApplicants;
    private final String ihtFormCompletedOnline;
    private String ihtReferenceNumber;
    private final String ihtFormId;
    private final String ihtGrossValue;
    private final String ihtNetValue;
    private final String ihtFormEstate;
    private String ihtEstateGrossValue;
    private String ihtEstateNetValue;
    private String ihtEstateNetQualifyingValue;
    private final String deceasedHadLateSpouseOrCivilPartner;
    private final String ihtUnusedAllowanceClaimed;
    private String deceasedDiedOnAfterSwitchDate;
    private String iht400Completed;
    private String iht400421Completed;
    private String iht207Completed;
    private String iht205Completed;
    private String iht205completedOnline;
    private final String exceptedEstate;
    private String iht400process;
    private final String ihtCode;
    private final String ihtGrossValueExceptedEstate;
    private final String ihtNetValueExceptedEstate;
    private String probateGrossValueIht400;
    private String probateNetValueIht400;
    private String iht421grossValue;
    private String iht421netValue;
    private String iht207grossValue;
    private String iht207netValue;
    private String ihtGrossValue205;
    private String ihtNetValue205;

    //common
    private final String formVersion;

}
