apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "probate-back-office"
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_j_to_z/probate-back-office
    github.com/project-slug: hmcts/probate-back-office
  tags:
    - java
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=probate
      title: "#probate on Slack"
      icon: chat
spec:
  type: service
  lifecycle: production
  owner: dcd_probate
