package uk.gov.hmcts.probate.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
public class SchedulerCrudAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CASEWORKER_PROBATE_SCHEDULER, Permission.C);
        grants.put(UserRole.CASEWORKER_PROBATE_SCHEDULER, Permission.R);
        grants.put(UserRole.CASEWORKER_PROBATE_SCHEDULER, Permission.U);
        grants.put(UserRole.CASEWORKER_PROBATE_SCHEDULER, Permission.D);
        return grants;
    }
}
