package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.ApplyforGrantPaperApplicationManApplyforGrantPaperApplicationManPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.ApplyforGrantPaperApplicationManApplyforGrantPaperApplicationManPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.ApplyforGrantPaperApplicationManApplyforGrantPaperApplicationManPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.ApplyforGrantPaperApplicationManApplyforGrantPaperApplicationManPage2CPage;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code applyforGrantPaperApplicationMan} for case type {@code GrantOfRepresentation}.
 */
@Component
public class ApplyforGrantPaperApplicationMan implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String APPLYFOR_GRANT_PAPER_APPLICATION_MAN = "applyforGrantPaperApplicationMan";

    /**
     * Registers event {@code applyforGrantPaperApplicationMan}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(APPLYFOR_GRANT_PAPER_APPLICATION_MAN)
            .initialState(State.CasePrinted)
            .name("PA1P/PA1A/Solicitors Manual")
            .description("Manual input to create applicantion")
            .displayOrder(117)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        ApplyforGrantPaperApplicationManApplyforGrantPaperApplicationManPage1Page.apply(fields);
        ApplyforGrantPaperApplicationManApplyforGrantPaperApplicationManPage2APage.apply(fields);
        ApplyforGrantPaperApplicationManApplyforGrantPaperApplicationManPage2BPage.apply(fields);
        ApplyforGrantPaperApplicationManApplyforGrantPaperApplicationManPage2CPage.apply(fields);
    }
}
