package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.ApplyForGrantApplyForGrantPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.ApplyForGrantApplyForGrantPage2Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code applyForGrant} for case type {@code GrantOfRepresentation}.
 */
@Component
public class ApplyForGrant implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String APPLY_FOR_GRANT = "applyForGrant";

    /**
     * Registers event {@code applyForGrant}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(APPLY_FOR_GRANT)
            .initialState(State.PAAppCreated)
            .name("PA application created")
            .description("Create a PA application")
            .displayOrder(118)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .grant(Set.of(Permission.C), UserRole.CITIZEN)
            .fields();
        ApplyForGrantApplyForGrantPage1Page.apply(fields);
        ApplyForGrantApplyForGrantPage2Page.apply(fields);
    }
}
