package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.ChangeOrganisationRequest;
import uk.gov.hmcts.probate.model.caseaccess.Organisation;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code applyNocDecision} for case type {@code GrantOfRepresentation}.
 */
@Component
public class ApplyNocDecision implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String APPLY_NOC_DECISION = "applyNocDecision";

    /**
     * Registers event {@code applyNocDecision}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(APPLY_NOC_DECISION)
            .forStates(State.CasePrinted, State.BOCaseStoppedAwaitRedec, State.BOCaseImported, State.BOCaseMatchingIssueGrant, State.BOCaseQA, State.BOCaseStopped, State.BOCaveatPermenant, State.BOSotGenerated, State.BOReadyToIssue, State.BORedecNotificationSent, State.BOCaseWorkerEscalation, State.Dormant, State.BORegistrarEscalation)
            .name("Apply NoC Decision")
            .description("Apply Notice of Change Request")
            .displayOrder(40)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .grant(Permission.CRUD, UserRole.CASEWORKER_APPROVER)
            .fields();
        fields.page("1");
        fields.pageLabel("Change Organisation Decision");
        fields.complex(CaseData::getChangeOrganisationRequestField, false)
                    .complex(ChangeOrganisationRequest::getOrganisationToAdd)
                    .optional(Organisation::getOrganisationID).done()
                    .complex(ChangeOrganisationRequest::getOrganisationToAdd)
                    .optional(Organisation::getOrganisationName).done()
                    .complex(ChangeOrganisationRequest::getOrganisationToRemove)
                    .optional(Organisation::getOrganisationID).done()
                    .complex(ChangeOrganisationRequest::getOrganisationToRemove)
                    .optional(Organisation::getOrganisationName).done()
                    .optional(ChangeOrganisationRequest::getCaseRoleId)
                    .optional(ChangeOrganisationRequest::getRequestTimestamp)
                    .optional(ChangeOrganisationRequest::getApprovalStatus).done();
    }
}
