package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.AssembleLetterForReissueAssembleLetterPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.AssembleLetterForReissueAssembleLetterPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.AssembleLetterForReissueAssembleLetterPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.AssembleLetterForReissueAssembleLetterPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.AssembleLetterForReissueAssembleLetterPage5Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code assembleLetterForReissue} for case type {@code GrantOfRepresentation}.
 */
@Component
public class AssembleLetterForReissue implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ASSEMBLE_LETTER_FOR_REISSUE = "assembleLetterForReissue";

    /**
     * Registers event {@code assembleLetterForReissue}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ASSEMBLE_LETTER_FOR_REISSUE)
            .forState(State.BOCaseStoppedReissue)
            .name("Assemble a letter")
            .displayOrder(42)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        AssembleLetterForReissueAssembleLetterPage1Page.apply(fields);
        AssembleLetterForReissueAssembleLetterPage2Page.apply(fields);
        AssembleLetterForReissueAssembleLetterPage3Page.apply(fields);
        AssembleLetterForReissueAssembleLetterPage4Page.apply(fields);
        AssembleLetterForReissueAssembleLetterPage5Page.apply(fields);
    }
}
