package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForReadyToIssue} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForReadyToIssue implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_READY_TO_ISSUE = "boAmendCaseDetailsForReadyToIssue";

    /**
     * Registers event {@code boAmendCaseDetailsForReadyToIssue}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_READY_TO_ISSUE)
            .forState(State.BOReadyToIssue)
            .name("Amend case details")
            .displayOrder(26)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
