package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForImportBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForImportBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForImportBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForImportBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForImportBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForImportBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForImportBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForImportBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForImportBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForImportBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForImportBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForImport} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForImport implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_IMPORT = "boAmendCaseDetailsForImport";

    /**
     * Registers event {@code boAmendCaseDetailsForImport}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_IMPORT)
            .forStateTransition(State.BOCaseImported, State.CaseCreated)
            .name("Amend case details for import")
            .displayOrder(37)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_ISSUER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoAmendCaseDetailsForImportBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForImportBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForImportBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForImportBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForImportBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForImportBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForImportBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForImportBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForImportBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForImportBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForImportBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
