package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForReadyForExamination} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForReadyForExamination implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_READY_FOR_EXAMINATION = "boAmendCaseDetailsForReadyForExamination";

    /**
     * Registers event {@code boAmendCaseDetailsForReadyForExamination}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_READY_FOR_EXAMINATION)
            .forState(State.BOReadyForExamination)
            .name("Amend case details")
            .displayOrder(20)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
