package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForCaveatPermenant} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForCaveatPermenant implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_CAVEAT_PERMENANT = "boAmendCaseDetailsForCaveatPermenant";

    /**
     * Registers event {@code boAmendCaseDetailsForCaveatPermenant}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_CAVEAT_PERMENANT)
            .forState(State.BOCaveatPermenant)
            .name("Amend case details")
            .displayOrder(25)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForCaveatPermenantBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
