package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForAwaitingDocumentation} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForAwaitingDocumentation implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_AWAITING_DOCUMENTATION = "boAmendCaseDetailsForAwaitingDocumentation";

    /**
     * Registers event {@code boAmendCaseDetailsForAwaitingDocumentation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_AWAITING_DOCUMENTATION)
            .forState(State.CasePrinted)
            .name("Amend case details")
            .displayOrder(19)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage9Page.apply(fields);
        BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForAwaitingDocumentationBoAmendCaseDetailsPage8Page.apply(fields);
    }
}
