package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForCaseCreated} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForCaseCreated implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_CASE_CREATED = "boAmendCaseDetailsForCaseCreated";

    /**
     * Registers event {@code boAmendCaseDetailsForCaseCreated}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_CASE_CREATED)
            .forState(State.CaseCreated)
            .name("Amend case details")
            .displayOrder(18)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForCaseCreatedBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
