package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetails} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetails implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS = "boAmendCaseDetails";

    /**
     * Registers event {@code boAmendCaseDetails}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS)
            .forAllStates()
            .name("Amend case details")
            .displayOrder(17)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoAmendCaseDetailsBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
