package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForPostGrantIssue} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForPostGrantIssue implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_POST_GRANT_ISSUE = "boAmendCaseDetailsForPostGrantIssue";

    /**
     * Registers event {@code boAmendCaseDetailsForPostGrantIssue}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_POST_GRANT_ISSUE)
            .forState(State.BOPostGrantIssued)
            .name("Amend case details")
            .displayOrder(34)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForPostGrantIssueBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
