package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForCaseQA} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForCaseQA implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_CASE_QA = "boAmendCaseDetailsForCaseQA";

    /**
     * Registers event {@code boAmendCaseDetailsForCaseQA}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_CASE_QA)
            .forState(State.BOCaseQA)
            .name("Amend case details")
            .displayOrder(27)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage9Page.apply(fields);
    }
}
