package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForCaseMatchingIssueGrant} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForCaseMatchingIssueGrant implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_CASE_MATCHING_ISSUE_GRANT = "boAmendCaseDetailsForCaseMatchingIssueGrant";

    /**
     * Registers event {@code boAmendCaseDetailsForCaseMatchingIssueGrant}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_CASE_MATCHING_ISSUE_GRANT)
            .forState(State.BOCaseMatchingIssueGrant)
            .name("Amend case details")
            .displayOrder(28)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingIssueGrantBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
