package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendLegalStatement} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendLegalStatement implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_LEGAL_STATEMENT = "boAmendLegalStatement";

    /**
     * Registers event {@code boAmendLegalStatement}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_LEGAL_STATEMENT)
            .forAllStates()
            .name("Amend legal statement")
            .description("Upload an amended legal statement")
            .displayOrder(38)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        fields.page("boAmendLegalStatementPage1");
        fields.mandatory(CaseData::getAmendedLegalStatement)
                    .caseEventFieldHint("Download the legal statement and amend it on your device. You can then upload it as a PDF in the next step.");
    }
}
