package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForRegistrarEscalation} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForRegistrarEscalation implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_REGISTRAR_ESCALATION = "boAmendCaseDetailsForRegistrarEscalation";

    /**
     * Registers event {@code boAmendCaseDetailsForRegistrarEscalation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_REGISTRAR_ESCALATION)
            .forState(State.BORegistrarEscalation)
            .name("Amend case details")
            .displayOrder(31)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForRegistrarEscalationBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
