package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForExamining} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForExamining implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_EXAMINING = "boAmendCaseDetailsForExamining";

    /**
     * Registers event {@code boAmendCaseDetailsForExamining}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_EXAMINING)
            .forState(State.BOExamining)
            .name("Amend case details")
            .displayOrder(23)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
