package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsPostGrantRegistrarEscalation} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsPostGrantRegistrarEscalation implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_POST_GRANT_REGISTRAR_ESCALATION = "boAmendCaseDetailsPostGrantRegistrarEscalation";

    /**
     * Registers event {@code boAmendCaseDetailsPostGrantRegistrarEscalation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_POST_GRANT_REGISTRAR_ESCALATION)
            .forState(State.BOPostGrantIssuedRegistrarEscalation)
            .name("Amend case details")
            .displayOrder(36)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
