package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForCaseStopped} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForCaseStopped implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_CASE_STOPPED = "boAmendCaseDetailsForCaseStopped";

    /**
     * Registers event {@code boAmendCaseDetailsForCaseStopped}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_CASE_STOPPED)
            .forState(State.BOCaseStopped)
            .name("Amend case details")
            .displayOrder(24)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
