package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForCaseClosed} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForCaseClosed implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_CASE_CLOSED = "boAmendCaseDetailsForCaseClosed";

    /**
     * Registers event {@code boAmendCaseDetailsForCaseClosed}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_CASE_CLOSED)
            .forState(State.BOCaseClosed)
            .name("Amend case details")
            .displayOrder(30)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN)
            .fields();
        BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForCaseClosedBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
