package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForGrantIssued} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForGrantIssued implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_GRANT_ISSUED = "boAmendCaseDetailsForGrantIssued";

    /**
     * Registers event {@code boAmendCaseDetailsForGrantIssued}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_GRANT_ISSUED)
            .forState(State.BOGrantIssued)
            .name("Amend case details")
            .displayOrder(29)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN)
            .fields();
        BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForGrantIssuedBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
