package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage10Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseForCaseStoppedReissue} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseForCaseStoppedReissue implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_FOR_CASE_STOPPED_REISSUE = "boAmendCaseForCaseStoppedReissue";

    /**
     * Registers event {@code boAmendCaseForCaseStoppedReissue}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_FOR_CASE_STOPPED_REISSUE)
            .forState(State.BOCaseStoppedReissue)
            .name("Amend case details")
            .displayOrder(32)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage1Page.apply(fields);
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage2Page.apply(fields);
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage2APage.apply(fields);
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage2BPage.apply(fields);
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage3Page.apply(fields);
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage4Page.apply(fields);
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage5Page.apply(fields);
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage6Page.apply(fields);
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage7Page.apply(fields);
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage8Page.apply(fields);
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage9Page.apply(fields);
        BoAmendCaseForCaseStoppedReissueBoExamineCaseReissueAmendDetailsPage10Page.apply(fields);
    }
}
