package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForCaseMatchingExamining} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForCaseMatchingExamining implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_CASE_MATCHING_EXAMINING = "boAmendCaseDetailsForCaseMatchingExamining";

    /**
     * Registers event {@code boAmendCaseDetailsForCaseMatchingExamining}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_CASE_MATCHING_EXAMINING)
            .forState(State.BOCaseMatchingExamining)
            .name("Amend case details")
            .displayOrder(21)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
