package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsForDormant} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsForDormant implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_FOR_DORMANT = "boAmendCaseDetailsForDormant";

    /**
     * Registers event {@code boAmendCaseDetailsForDormant}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_FOR_DORMANT)
            .forState(State.Dormant)
            .name("Amend case details")
            .displayOrder(22)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsForDormantBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
