package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boAmendCaseDetailsGrantRegistrarEscalation} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoAmendCaseDetailsGrantRegistrarEscalation implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_AMEND_CASE_DETAILS_GRANT_REGISTRAR_ESCALATION = "boAmendCaseDetailsGrantRegistrarEscalation";

    /**
     * Registers event {@code boAmendCaseDetailsGrantRegistrarEscalation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_AMEND_CASE_DETAILS_GRANT_REGISTRAR_ESCALATION)
            .forState(State.BOGrantIssuedRegistrarEscalation)
            .name("Amend case details")
            .displayOrder(35)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage1Page.apply(fields);
        BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage2Page.apply(fields);
        BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage2APage.apply(fields);
        BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage2BPage.apply(fields);
        BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage3Page.apply(fields);
        BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage4Page.apply(fields);
        BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage5Page.apply(fields);
        BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage6Page.apply(fields);
        BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage7Page.apply(fields);
        BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage8Page.apply(fields);
        BoAmendCaseDetailsGrantRegistrarEscalationBoAmendCaseDetailsPage9Page.apply(fields);
    }
}
