package uk.gov.hmcts.probate.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boEscalateToRegistrar} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoEscalateToRegistrar implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_ESCALATE_TO_REGISTRAR = "boEscalateToRegistrar";

    /**
     * Registers event {@code boEscalateToRegistrar}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_ESCALATE_TO_REGISTRAR)
            .forStateTransition(EnumSet.of(State.CasePrinted, State.BOCaseStoppedAwaitRedec, State.BOCaseImported, State.BOCaseMatchingIssueGrant, State.BOCaseQA, State.BOCaseStopped, State.BOCaveatPermenant, State.BOSotGenerated, State.BOReadyToIssue, State.BORedecNotificationSent, State.BOCaseWorkerEscalation), State.BORegistrarEscalation)
            .name("Escalate to registrar")
            .displayOrder(70)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        fields.page("registrarEscalateReasonPage1");
        fields.readonly(CaseData::getRegistrarEscalateLabel1);
        fields.readonly(CaseData::getRegistrarEscalateLabel2);
        fields.mandatory(CaseData::getRegistrarEscalateReason);
    }
}
