package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage10Page;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage2APage;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage2BPage;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage8Page;
import uk.gov.hmcts.probate.ccd.event.page.BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage9Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boExamineCaseReissueAmendDetails} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoExamineCaseReissueAmendDetails implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_EXAMINE_CASE_REISSUE_AMEND_DETAILS = "boExamineCaseReissueAmendDetails";

    /**
     * Registers event {@code boExamineCaseReissueAmendDetails}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_EXAMINE_CASE_REISSUE_AMEND_DETAILS)
            .forState(State.BOExaminingReissue)
            .name("Amend case details")
            .displayOrder(33)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage1Page.apply(fields);
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage2Page.apply(fields);
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage2APage.apply(fields);
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage2BPage.apply(fields);
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage3Page.apply(fields);
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage4Page.apply(fields);
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage5Page.apply(fields);
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage6Page.apply(fields);
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage7Page.apply(fields);
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage8Page.apply(fields);
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage9Page.apply(fields);
        BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage10Page.apply(fields);
    }
}
