package uk.gov.hmcts.probate.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boExamineCaseReissue} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoExamineCaseReissue implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_EXAMINE_CASE_REISSUE = "boExamineCaseReissue";

    /**
     * Registers event {@code boExamineCaseReissue}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_EXAMINE_CASE_REISSUE)
            .forStateTransition(EnumSet.of(State.BOGrantIssued, State.BOGrantIssuedRegistrarEscalation), State.BOExaminingReissue)
            .name("Examine case (reissue grant)")
            .description("Move the case to the Examining state reissue")
            .displayOrder(74)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        fields.page("boExamineCaseReissuePage1");
        fields.pageLabel("Reason for reissue");
        fields.mandatory(CaseData::getOrderNeeded);
        fields.mandatory(CaseData::getReissueReason);
    }
}
