package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoFindMatchedReadyToIssueBoFindMatchedReadyToIssuePage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoFindMatchedReadyToIssueBoFindMatchedReadyToIssuePage2Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boFindMatchedReadyToIssue} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoFindMatchedReadyToIssue implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_FIND_MATCHED_READY_TO_ISSUE = "boFindMatchedReadyToIssue";

    /**
     * Registers event {@code boFindMatchedReadyToIssue}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_FIND_MATCHED_READY_TO_ISSUE)
            .forStateTransition(State.BOCaseQA, State.BOCaseMatchingIssueGrant)
            .name("Find matches (Issue grant)")
            .displayOrder(88)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        BoFindMatchedReadyToIssueBoFindMatchedReadyToIssuePage1Page.apply(fields);
        BoFindMatchedReadyToIssueBoFindMatchedReadyToIssuePage2Page.apply(fields);
    }
}
