package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoFindMatchesForReadyForExaminingBoFindMatchesForReadyForExaminingP1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoFindMatchesForReadyForExaminingBoFindMatchesForReadyForExaminingP2Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boFindMatchesForReadyForExamining} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoFindMatchesForReadyForExamining implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_FIND_MATCHES_FOR_READY_FOR_EXAMINING = "boFindMatchesForReadyForExamining";

    /**
     * Registers event {@code boFindMatchesForReadyForExamining}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_FIND_MATCHES_FOR_READY_FOR_EXAMINING)
            .forStateTransition(State.BOReadyForExamination, State.BOCaseMatchingExamining)
            .name("Find matches (Examining)")
            .displayOrder(84)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SOLICITOR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        BoFindMatchesForReadyForExaminingBoFindMatchesForReadyForExaminingP1Page.apply(fields);
        BoFindMatchesForReadyForExaminingBoFindMatchesForReadyForExaminingP2Page.apply(fields);
    }
}
