package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoFindMatchedCaseStoppedBoFindMatchedCaseStoppedPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoFindMatchedCaseStoppedBoFindMatchedCaseStoppedPage2Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boFindMatchedCaseStopped} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoFindMatchedCaseStopped implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_FIND_MATCHED_CASE_STOPPED = "boFindMatchedCaseStopped";

    /**
     * Registers event {@code boFindMatchedCaseStopped}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_FIND_MATCHED_CASE_STOPPED)
            .forState(State.BOCaseStopped)
            .name("Find matched cases")
            .description("Find matched case")
            .displayOrder(78)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        BoFindMatchedCaseStoppedBoFindMatchedCaseStoppedPage1Page.apply(fields);
        BoFindMatchedCaseStoppedBoFindMatchedCaseStoppedPage2Page.apply(fields);
    }
}
