package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoFindMatchedCasesForCaseStoppedBoFindMatchedCasesForCaseStoppedPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoFindMatchedCasesForCaseStoppedBoFindMatchedCasesForCaseStoppedPage2Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boFindMatchedCasesForCaseStopped} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoFindMatchedCasesForCaseStopped implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_FIND_MATCHED_CASES_FOR_CASE_STOPPED = "boFindMatchedCasesForCaseStopped";

    /**
     * Registers event {@code boFindMatchedCasesForCaseStopped}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_FIND_MATCHED_CASES_FOR_CASE_STOPPED)
            .forStateTransition(State.BOCaseStopped, State.BOCaseMatchingIssueGrant)
            .name("Find matches (Issue grant)")
            .displayOrder(85)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        BoFindMatchedCasesForCaseStoppedBoFindMatchedCasesForCaseStoppedPage1Page.apply(fields);
        BoFindMatchedCasesForCaseStoppedBoFindMatchedCasesForCaseStoppedPage2Page.apply(fields);
    }
}
