package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage8Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boFullCaseAmendAwaitRedec} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoFullCaseAmendAwaitRedec implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_FULL_CASE_AMEND_AWAIT_REDEC = "boFullCaseAmendAwaitRedec";

    /**
     * Registers event {@code boFullCaseAmendAwaitRedec}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_FULL_CASE_AMEND_AWAIT_REDEC)
            .forState(State.BOCaseStoppedAwaitRedec)
            .name("Full case amend")
            .description("amend the full case")
            .displayOrder(91)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage1Page.apply(fields);
        BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage2Page.apply(fields);
        BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage3Page.apply(fields);
        BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage4Page.apply(fields);
        BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage5Page.apply(fields);
        BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage6Page.apply(fields);
        BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage7Page.apply(fields);
        BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage8Page.apply(fields);
    }
}
