package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boGenerateGrantPreviewForCaseQA} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoGenerateGrantPreviewForCaseQA implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_GENERATE_GRANT_PREVIEW_FOR_CASE_QA = "boGenerateGrantPreviewForCaseQA";

    /**
     * Registers event {@code boGenerateGrantPreviewForCaseQA}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(BO_GENERATE_GRANT_PREVIEW_FOR_CASE_QA)
            .forStateTransition(State.BOCaseQA, State.BOReadyToIssue)
            .name("Generate grant preview")
            .displayOrder(95)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER);
    }
}
