package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoNotifyRedeclarationSOTBoNotifyRedeclarationSOTPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoNotifyRedeclarationSOTBoNotifyRedeclarationSOTPage2Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boNotifyRedeclarationSOT} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoNotifyRedeclarationSOT implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_NOTIFY_REDECLARATION_SOT = "boNotifyRedeclarationSOT";

    /**
     * Registers event {@code boNotifyRedeclarationSOT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_NOTIFY_REDECLARATION_SOT)
            .forStateTransition(State.BOSotGenerated, State.BORedecNotificationSent)
            .name("Send redec notification")
            .description("Send redeclaration notification")
            .displayOrder(143)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        BoNotifyRedeclarationSOTBoNotifyRedeclarationSOTPage1Page.apply(fields);
        BoNotifyRedeclarationSOTBoNotifyRedeclarationSOTPage2Page.apply(fields);
    }
}
