package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ExecutorsApplyingNotification;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boRedeclarationComplete} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoRedeclarationComplete implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_REDECLARATION_COMPLETE = "boRedeclarationComplete";

    /**
     * Registers event {@code boRedeclarationComplete}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_REDECLARATION_COMPLETE)
            .forStateTransition(State.BORedecNotificationSent, State.BOCaseStopped)
            .name("Redeclaration complete")
            .displayOrder(129)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_RPAROBOT, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        fields.page("boRequestInfoForCaseStoppedPage1");
        fields.complex(CaseData::getExecutorsApplyingNotifications).done();
        fields.complex(CaseData::getExecutorsApplyingNotifications, ExecutorsApplyingNotification.class)
                    .readonly(ExecutorsApplyingNotification::getName)
                    .eventLabel("Name of the executor")
                    .readonly(ExecutorsApplyingNotification::getEmail)
                    .fieldShowCondition("name=\"NeverShowThisField\"")
                    .eventLabel("Email of the executor")
                    .readonly(ExecutorsApplyingNotification::getAddress)
                    .fieldShowCondition("name=\"NeverShowThisField\"")
                    .eventLabel("Address of the executor")
                    .mandatory(ExecutorsApplyingNotification::getNotification)
                    .eventLabel("Do you wish to send a notification?")
                    .mandatory(ExecutorsApplyingNotification::getResponseReceived)
                    .eventLabel("Has a response been received?").done();
    }
}
