package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage6Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code boRequestInfoForCaseStopped} for case type {@code GrantOfRepresentation}.
 */
@Component
public class BoRequestInfoForCaseStopped implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String BO_REQUEST_INFO_FOR_CASE_STOPPED = "boRequestInfoForCaseStopped";

    /**
     * Registers event {@code boRequestInfoForCaseStopped}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(BO_REQUEST_INFO_FOR_CASE_STOPPED)
            .forStates(State.BOCaseStopped, State.BOGrantIssued, State.BOPostGrantIssued, State.BOCaseStoppedReissue)
            .name("Request information")
            .displayOrder(135)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage1Page.apply(fields);
        BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage2Page.apply(fields);
        BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage3Page.apply(fields);
        BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage4Page.apply(fields);
        BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage5Page.apply(fields);
        BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage6Page.apply(fields);
    }
}
