package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code changeDob} for case type {@code GrantOfRepresentation}.
 */
@Component
public class ChangeDob implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CHANGE_DOB = "changeDob";

    /**
     * Registers event {@code changeDob}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CHANGE_DOB)
            .forAllStates()
            .name("Change DOB")
            .displayOrder(56)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        fields.page("changeDodPage1");
        fields.readonlyNoSummary(CaseData::getDeceasedForenames);
        fields.readonlyNoSummary(CaseData::getDeceasedSurname);
        fields.mandatoryNoSummary(CaseData::getDeceasedDob);
    }
}
