package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.CreateCaseFromBulkScanCreateCaseFromBulkScanPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.CreateCaseFromBulkScanCreateCaseFromBulkScanPage2Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code createCaseFromBulkScan} for case type {@code GrantOfRepresentation}.
 */
@Component
public class CreateCaseFromBulkScan implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_CASE_FROM_BULK_SCAN = "createCaseFromBulkScan";

    /**
     * Registers event {@code createCaseFromBulkScan}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CREATE_CASE_FROM_BULK_SCAN)
            .initialState(State.CasePrinted)
            .name("Case created from bulk scan")
            .description("Create a case from an application")
            .displayOrder(50)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .fields();
        CreateCaseFromBulkScanCreateCaseFromBulkScanPage1Page.apply(fields);
        CreateCaseFromBulkScanCreateCaseFromBulkScanPage2Page.apply(fields);
    }
}
