package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code grantDraftReissue} for case type {@code GrantOfRepresentation}.
 */
@Component
public class GrantDraftReissue implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String GRANT_DRAFT_REISSUE = "grantDraftReissue";

    /**
     * Registers event {@code grantDraftReissue}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(GRANT_DRAFT_REISSUE)
            .forState(State.BOExaminingReissue)
            .name("Generate grant draft (reissue)")
            .description("Generate grant preview (reissue)")
            .displayOrder(92)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        fields.page("grantDraftReissuePage1");
        fields.mandatory(CaseData::getReissueReasonNotation);
        fields.mandatory(CaseData::getReissueDate);
    }
}
