package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code handleEvidence} for case type {@code GrantOfRepresentation}.
 */
@Component
public class HandleEvidence implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String HANDLE_EVIDENCE = "handleEvidence";

    /**
     * Registers event {@code handleEvidence}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(HANDLE_EVIDENCE)
            .forAllStates()
            .name("Handle supplementary evidence")
            .displayOrder(104)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_RPAROBOT, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .grant(Set.of(Permission.U), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Permission.CRU, UserRole.CASEWORKER_PROBATE_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        fields.page("evidenceHandledPage1");
        fields.mandatoryNoSummary(CaseData::getCaseType)
                    .fieldShowCondition("[STATE]=\"NeverShow\"");
        fields.optionalNoSummary(CaseData::getBoHandoffReasonList)
                    .fieldShowCondition("[STATE]=\"NeverShow\"");
        fields.mandatoryNoSummary(CaseData::getEvidenceHandled);
    }
}
