package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code keepDraft} for case type {@code GrantOfRepresentation}.
 */
@Component
public class KeepDraft implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String KEEP_DRAFT = "keepDraft";

    /**
     * Registers event {@code keepDraft}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(KEEP_DRAFT)
            .forState(State.Pending)
            .name("Keep draft")
            .displayOrder(198)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CITIZEN);
    }
}
