package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.Aliases;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.DeathRecord;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code levSelectFromMultipleRecords} for case type {@code GrantOfRepresentation}.
 */
@Component
public class LevSelectFromMultipleRecords implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String LEV_SELECT_FROM_MULTIPLE_RECORDS = "levSelectFromMultipleRecords";

    /**
     * Registers event {@code levSelectFromMultipleRecords}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(LEV_SELECT_FROM_MULTIPLE_RECORDS)
            .forAllStates()
            .name("Select from multiple records")
            .displayOrder(142)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SUPERUSER, UserRole.CASEWORKER_PROBATE_SYSTEMUPDATE)
            .fields();
        fields.page("levSelectFromMultipleRecordsPage1");
        fields.readonlyNoSummary(CaseData::getNumberOfDeathRecords);
        fields.complex(CaseData::getDeathRecords, false).done();
        fields.complex(CaseData::getDeathRecords, DeathRecord.class)
                    .readonly(DeathRecord::getSystemNumber)
                    .readonly(DeathRecord::getName)
                    .readonly(DeathRecord::getAliases)
                    .readonly(DeathRecord::getDateOfBirth)
                    .readonly(DeathRecord::getSex)
                    .readonly(DeathRecord::getAddress)
                    .readonly(DeathRecord::getDateOfDeath)
                    .mandatory(DeathRecord::getValid)
                    .complex(DeathRecord::getAliases, Aliases.class)
                    .readonly(Aliases::getType).done()
                    .complex(DeathRecord::getAliases, Aliases.class)
                    .readonly(Aliases::getPrefix).done()
                    .complex(DeathRecord::getAliases, Aliases.class)
                    .readonly(Aliases::getForenames).done()
                    .complex(DeathRecord::getAliases, Aliases.class)
                    .readonly(Aliases::getLastName).done()
                    .complex(DeathRecord::getAliases, Aliases.class)
                    .readonly(Aliases::getSuffix).done().done();
    }
}
