package uk.gov.hmcts.probate.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code makeCaseDormant} for case type {@code GrantOfRepresentation}.
 */
@Component
public class MakeCaseDormant implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MAKE_CASE_DORMANT = "makeCaseDormant";

    /**
     * Registers event {@code makeCaseDormant}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(MAKE_CASE_DORMANT)
            .forStateTransition(EnumSet.allOf(State.class), State.Dormant)
            .name("Make case dormant")
            .description("Make case dormant by scheduler")
            .displayOrder(110)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SOLICITOR, UserRole.CASEWORKER_PROBATE_SUPERUSER, UserRole.CITIZEN)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SYSTEMUPDATE);
    }
}
