package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.ccd.sdk.type.TTL;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code manageCaseTTL} for case type {@code GrantOfRepresentation}.
 */
@Component
public class ManageCaseTTL implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_CASE_TTL = "manageCaseTTL";

    /**
     * Registers event {@code manageCaseTTL}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(MANAGE_CASE_TTL)
            .forAllStates()
            .name("Manage Case TTL")
            .displayOrder(199)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.TTL_PROFILE)
            .fields();
        fields.page("manageCaseTTLPage1");
        fields.complex(CaseData::getManageCaseTtl)
                    .readonly(TTL::getSystemTTL)
                    .eventLabel("System TTL")
                    .optional(TTL::getOverrideTTL)
                    .eventLabel("Override TTL")
                    .optional(TTL::getSuspended)
                    .eventLabel("Suspend Deletion").done();
    }
}
