package uk.gov.hmcts.probate.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code moveToCWEscalation} for case type {@code GrantOfRepresentation}.
 */
@Component
public class MoveToCWEscalation implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MOVE_TO_CWESCALATION = "moveToCWEscalation";

    /**
     * Registers event {@code moveToCWEscalation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(MOVE_TO_CWESCALATION)
            .forStateTransition(EnumSet.of(State.BOExamining, State.BOCaseStopped, State.BORegistrarEscalation, State.BOReadyForExamination, State.BOCaveatPermenant, State.BOReadyToIssue, State.BOCaseQA, State.BOCaseMatchingIssueGrant, State.BOCaseMatchingExamining, State.BOCaseStoppedAwaitRedec, State.CasePrinted), State.BOCaseWorkerEscalation)
            .name("SME Referral")
            .displayOrder(146)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR, UserRole.CITIZEN);
    }
}
