package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.DocumentUpload;
import uk.gov.hmcts.probate.model.ccd.raw.request.ProbateDocument;
import uk.gov.hmcts.probate.model.ccd.raw.ScannedDocument;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code removeDocuments} for case type {@code GrantOfRepresentation}.
 */
@Component
public class RemoveDocuments implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REMOVE_DOCUMENTS = "removeDocuments";

    /**
     * Registers event {@code removeDocuments}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REMOVE_DOCUMENTS)
            .forAllStates()
            .name("Remove documents from case")
            .displayOrder(133)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .fields();
        fields.page("removeDocumentsPage1");
        fields.complex(CaseData::getProbateDocumentsGenerated, false).done();
        fields.complex(CaseData::getProbateDocumentsGenerated, ProbateDocument.class)
                    .readonly(ProbateDocument::getDocumentType)
                    .readonly(ProbateDocument::getDocumentLink)
                    .readonly(ProbateDocument::getDocumentDateAdded)
                    .readonly(ProbateDocument::getDocumentGeneratedBy).done();
        fields.complex(CaseData::getBoDocumentsUploaded, false).done();
        fields.complex(CaseData::getBoDocumentsUploaded, DocumentUpload.class)
                    .readonly(DocumentUpload::getDocumentType)
                    .readonly(DocumentUpload::getDocumentLink)
                    .readonly(DocumentUpload::getComment).done();
        fields.complex(CaseData::getScannedDocuments, false).done();
        fields.complex(CaseData::getScannedDocuments, ScannedDocument.class)
                    .readonly(ScannedDocument::getControlNumber)
                    .readonly(ScannedDocument::getFileName)
                    .readonly(ScannedDocument::getType)
                    .readonly(ScannedDocument::getSubtype)
                    .readonly(ScannedDocument::getScannedDate)
                    .readonly(ScannedDocument::getUrl)
                    .readonly(ScannedDocument::getExceptionRecordReference)
                    .readonly(ScannedDocument::getDeliveryDate).done();
        fields.readonlyNoSummary(CaseData::getOriginalDocuments)
                    .fieldShowCondition("[STATE]=\"NeverShowThisField\"");
    }
}
