package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code scheduledUpdateGrantDelayNotificationSent} for case type {@code GrantOfRepresentation}.
 */
@Component
public class ScheduledUpdateGrantDelayNotificationSent implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SCHEDULED_UPDATE_GRANT_DELAY_NOTIFICATION_SENT = "scheduledUpdateGrantDelayNotificationSent";

    /**
     * Registers event {@code scheduledUpdateGrantDelayNotificationSent}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(SCHEDULED_UPDATE_GRANT_DELAY_NOTIFICATION_SENT)
            .forAllStates()
            .name("Grant delay notification sent")
            .displayOrder(100)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SUPERUSER, UserRole.CASEWORKER_PROBATE_SYSTEMUPDATE)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SCHEDULER);
    }
}
