package uk.gov.hmcts.probate.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code serviceRequestPaymentSuccess} for case type {@code GrantOfRepresentation}.
 */
@Component
public class ServiceRequestPaymentSuccess implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SERVICE_REQUEST_PAYMENT_SUCCESS = "serviceRequestPaymentSuccess";

    /**
     * Registers event {@code serviceRequestPaymentSuccess}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(SERVICE_REQUEST_PAYMENT_SUCCESS)
            .forStateTransition(EnumSet.allOf(State.class), State.CasePrinted)
            .name("ServiceRequest payment success")
            .description("Callback to update payment info upon Service Request Payment invocation")
            .displayOrder(145)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SOLICITOR, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SYSTEMUPDATE);
    }
}
