package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateApplicationSolicitorUpdateApplicationPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateApplicationSolicitorUpdateApplicationPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateApplicationSolicitorUpdateApplicationPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateApplicationSolicitorUpdateApplicationPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateApplicationSolicitorUpdateApplicationPage5Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateApplicationSolicitorUpdateApplicationPage6Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateApplicationSolicitorUpdateApplicationPage7Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateApplicationSolicitorUpdateApplicationPage8Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code solicitorUpdateApplication} for case type {@code GrantOfRepresentation}.
 */
@Component
public class SolicitorUpdateApplication implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SOLICITOR_UPDATE_APPLICATION = "solicitorUpdateApplication";

    /**
     * Registers event {@code solicitorUpdateApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SOLICITOR_UPDATE_APPLICATION)
            .forState(State.SolAppCreatedDeceasedDtls)
            .name("Deceased details")
            .description("Probate practitioner updates deceased details")
            .displayOrder(62)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        SolicitorUpdateApplicationSolicitorUpdateApplicationPage1Page.apply(fields);
        SolicitorUpdateApplicationSolicitorUpdateApplicationPage2Page.apply(fields);
        SolicitorUpdateApplicationSolicitorUpdateApplicationPage3Page.apply(fields);
        SolicitorUpdateApplicationSolicitorUpdateApplicationPage4Page.apply(fields);
        SolicitorUpdateApplicationSolicitorUpdateApplicationPage5Page.apply(fields);
        SolicitorUpdateApplicationSolicitorUpdateApplicationPage6Page.apply(fields);
        SolicitorUpdateApplicationSolicitorUpdateApplicationPage7Page.apply(fields);
        SolicitorUpdateApplicationSolicitorUpdateApplicationPage8Page.apply(fields);
    }
}
