package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateProbateSolicitorUpdateProbatePage1Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateProbateSolicitorUpdateProbatePage2Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateProbateSolicitorUpdateProbatePage3Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateProbateSolicitorUpdateProbatePage4Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateProbateSolicitorUpdateProbatePage5Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateProbateSolicitorUpdateProbatePage6Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code solicitorUpdateProbate} for case type {@code GrantOfRepresentation}.
 */
@Component
public class SolicitorUpdateProbate implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SOLICITOR_UPDATE_PROBATE = "solicitorUpdateProbate";

    /**
     * Registers event {@code solicitorUpdateProbate}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SOLICITOR_UPDATE_PROBATE)
            .forStateTransition(State.SolProbateCreated, State.SolAppUpdated)
            .name("Grant of probate details")
            .description("Solicitor updates grant of probate details")
            .displayOrder(101)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        SolicitorUpdateProbateSolicitorUpdateProbatePage1Page.apply(fields);
        SolicitorUpdateProbateSolicitorUpdateProbatePage2Page.apply(fields);
        SolicitorUpdateProbateSolicitorUpdateProbatePage3Page.apply(fields);
        SolicitorUpdateProbateSolicitorUpdateProbatePage4Page.apply(fields);
        SolicitorUpdateProbateSolicitorUpdateProbatePage5Page.apply(fields);
        SolicitorUpdateProbateSolicitorUpdateProbatePage6Page.apply(fields);
    }
}
