package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code solicitorPaymentSuccessCase} for case type {@code GrantOfRepresentation}.
 */
@Component
public class SolicitorPaymentSuccessCase implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SOLICITOR_PAYMENT_SUCCESS_CASE = "solicitorPaymentSuccessCase";

    /**
     * Registers event {@code solicitorPaymentSuccessCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(SOLICITOR_PAYMENT_SUCCESS_CASE)
            .forStateTransition(State.CaseCreated, State.CasePrinted)
            .name("Payment Successful")
            .description("Manual override case into Awaiting Documentation state")
            .displayOrder(122)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SUPERUSER, UserRole.CASEWORKER_PROBATE_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SOLICITOR);
    }
}
