package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorCreateApplicationSolicitorCreateApplicationPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorCreateApplicationSolicitorCreateApplicationPage2Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code solicitorCreateApplication} for case type {@code GrantOfRepresentation}.
 */
@Component
public class SolicitorCreateApplication implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SOLICITOR_CREATE_APPLICATION = "solicitorCreateApplication";

    /**
     * Registers event {@code solicitorCreateApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SOLICITOR_CREATE_APPLICATION)
            .initialState(State.SolAppCreatedDeceasedDtls)
            .name("Apply for probate")
            .description("Solicitor begins a new application with firm and case details")
            .displayOrder(39)
            .showSummary()
            .showEventNotes()
            .canSaveDraft()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SYSTEMUPDATE)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        SolicitorCreateApplicationSolicitorCreateApplicationPage1Page.apply(fields);
        SolicitorCreateApplicationSolicitorCreateApplicationPage2Page.apply(fields);
    }
}
