package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorReviewAndConfirmSolicitorConfirmPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorReviewAndConfirmSolicitorConfirmPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorReviewAndConfirmSolicitorConfirmPage4Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage4Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code solicitorReviewAndConfirm} for case type {@code GrantOfRepresentation}.
 */
@Component
public class SolicitorReviewAndConfirm implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SOLICITOR_REVIEW_AND_CONFIRM = "solicitorReviewAndConfirm";

    /**
     * Registers event {@code solicitorReviewAndConfirm}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SOLICITOR_REVIEW_AND_CONFIRM)
            .forStateTransition(State.SolAppUpdated, State.CaseCreated)
            .name("Complete application")
            .description("Solicitors reviews legal statement and confirms")
            .displayOrder(57)
            .showSummary(false)
            .showEventNotes()
            .endButtonLabel("Save or Submit application")
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage1Page.apply(fields);
        SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage2Page.apply(fields);
        SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage3Page.apply(fields);
        SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage4Page.apply(fields);
        SolicitorReviewAndConfirmSolicitorConfirmPage2Page.apply(fields);
        SolicitorReviewAndConfirmSolicitorConfirmPage3Page.apply(fields);
        SolicitorReviewAndConfirmSolicitorConfirmPage4Page.apply(fields);
    }
}
