package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateIntestacySolicitorUpdateIntestacyPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateIntestacySolicitorUpdateIntestacyPage2Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateIntestacySolicitorUpdateIntestacyPage3Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateIntestacySolicitorUpdateIntestacyPage4Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code solicitorUpdateIntestacy} for case type {@code GrantOfRepresentation}.
 */
@Component
public class SolicitorUpdateIntestacy implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SOLICITOR_UPDATE_INTESTACY = "solicitorUpdateIntestacy";

    /**
     * Registers event {@code solicitorUpdateIntestacy}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SOLICITOR_UPDATE_INTESTACY)
            .forStateTransition(State.SolIntestacyCreated, State.SolAppUpdated)
            .name("Intestacy details")
            .description("Solicitor updates intestacy details")
            .displayOrder(108)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        SolicitorUpdateIntestacySolicitorUpdateIntestacyPage1Page.apply(fields);
        SolicitorUpdateIntestacySolicitorUpdateIntestacyPage2Page.apply(fields);
        SolicitorUpdateIntestacySolicitorUpdateIntestacyPage3Page.apply(fields);
        SolicitorUpdateIntestacySolicitorUpdateIntestacyPage4Page.apply(fields);
    }
}
