package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateAppSolDtlsSolicitorUpdateAppSolDtlsPage1Page;
import uk.gov.hmcts.probate.ccd.event.page.SolicitorUpdateAppSolDtlsSolicitorUpdateAppSolDtlsPage2Page;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code solicitorUpdateAppSolDtls} for case type {@code GrantOfRepresentation}.
 */
@Component
public class SolicitorUpdateAppSolDtls implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SOLICITOR_UPDATE_APP_SOL_DTLS = "solicitorUpdateAppSolDtls";

    /**
     * Registers event {@code solicitorUpdateAppSolDtls}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SOLICITOR_UPDATE_APP_SOL_DTLS)
            .forStateTransition(State.SolAppCreatedSolicitorDtls, State.SolAppCreatedDeceasedDtls)
            .name("Probate practitioner details")
            .description("Probate practitioner updates probate practitioner details")
            .displayOrder(126)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        SolicitorUpdateAppSolDtlsSolicitorUpdateAppSolDtlsPage1Page.apply(fields);
        SolicitorUpdateAppSolDtlsSolicitorUpdateAppSolDtlsPage2Page.apply(fields);
    }
}
