package uk.gov.hmcts.probate.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code solicitorDeleteApplicationCreationSolDtls} for case type {@code GrantOfRepresentation}.
 */
@Component
public class SolicitorDeleteApplicationCreationSolDtls implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SOLICITOR_DELETE_APPLICATION_CREATION_SOL_DTLS = "solicitorDeleteApplicationCreationSolDtls";

    /**
     * Registers event {@code solicitorDeleteApplicationCreationSolDtls}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SOLICITOR_DELETE_APPLICATION_CREATION_SOL_DTLS)
            .forStateTransition(State.SolAppCreatedSolicitorDtls, State.Deleted)
            .name("Delete")
            .description("Delete application")
            .displayOrder(64)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .fields();
        fields.page("deleteForCreation0");
        fields.readonlyNoSummary(CaseData::getDeleteApplication);
    }
}
