package uk.gov.hmcts.probate.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Event {@code SYSTEM_MAINTENANCE} for case type {@code GrantOfRepresentation}.
 */
@Component
public class SYSTEMMAINTENANCE implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE";

    /**
     * Registers event {@code SYSTEM_MAINTENANCE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(SYSTEM_MAINTENANCE)
            .forAllStates()
            .name("System maintenance")
            .description("Maintenance updates to cases, made automatically by the system")
            .displayOrder(157)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PROBATE_CASEADMIN, UserRole.CASEWORKER_PROBATE_CASEOFFICER, UserRole.CASEWORKER_PROBATE_ISSUER, UserRole.CASEWORKER_PROBATE_REGISTRAR, UserRole.CASEWORKER_PROBATE_SCHEDULER, UserRole.CASEWORKER_PROBATE_SOLICITOR, UserRole.CASEWORKER_PROBATE_SUPERUSER, UserRole.CASEWORKER_PROBATE_SYSTEMUPDATE, UserRole.CITIZEN);
    }
}
