INSERT INTO WILLS_FLAT
(
ID, RK_NUMBER, PROBATE_NUMBER, PROBATE_VERSION, DECEASED_ID, DECEASED_FORENAMES, DECEASED_SURNAME, DATE_OF_BIRTH, DATE_OF_DEATH1, DATE_OF_DEATH2, ALIAS_NAMES,
RECORD_KEEPERS_TEXT, CCD_CASE_NO, DNM_IND, LAST_MODIFIED
)VALUES (
nextval('WILLS_FLAT_SEQ'), 'RK-1', 'PRO-01', 1, 1, '[FORENAME_REPLACE]', '[SURNAME_REPLACE]', '01/01/1900', '01/01/2018', '02/02/2018', '[ALIAS_REPLACE]',
'RK-Text', null, 'N', NOW()
);
