package uk.gov.hmcts.probate.model;

public enum NotificationType {
    FIRST_STOP_REMINDER,
    SECOND_STOP_REMINDER,
    HSE_REMINDER,
    DORMANT_WARNING,
    UNSUBMITTED_APPLICATION,
    DECLARATION_NOT_SIGNED,
    DORMANT_REMINDER
}