package uk.gov.hmcts.probate.model;

public enum State {
    DOCUMENTS_RECEIVED,
    CASE_STOPPED,
    CASE_STOPPED_CAVEAT,
    GRANT_ISSUED,
    GRANT_REISSUED,
    GENERAL_CAVEAT_MESSAGE,
    GRANT_RAISED,
    CAVEAT_RAISED,
    CAVEAT_EXTEND,
    CAVEAT_WITHDRAW,
    CAVEAT_RAISED_SOLS,
    CASE_STOPPED_REQUEST_INFORMATION,
    REDECLARATION_SOT
}

