version: '3'
services:
  ccd-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: ccd-elasticsearch
    depends_on:
      - "ccd-data-store-api"
    environment:
      - cluster.name=ccd-docker-es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - action.auto_create_index=.security*,.watches,.triggered_watches,.watcher-history-*,.logstash_dead_letter,.ml*,grantofrepresentation_cases,caveat_cases,legacy_cases,standingsearch_cases,willlodgement_cases
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - compose_default

  ccd-logstash:
    image: "ccd-logstash:probate"
    container_name: ccd-logstash
    depends_on:
          - "ccd-elasticsearch"
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
      - APPINSIGHTS_INSTRUMENTATIONKEY=dummy
    networks:
      - compose_default

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - ccd-elasticsearch


#  probate-man-database:
#    build:
#      context: ../docker/database
#    ports:
#      - 5344:5432
#    healthcheck:
#      test: psql -c 'select 1' -d postgres -U postgres
#      retries: 2
#    #mem_limit: 160m
#    #memswap_limit: 0

#  logstash-probateman:
#    build: ../docker/logstash-probateman/.
#    container_name: logstash-probateman
#    command: bash -c "bin/logstash-plugin install logstash-filter-json_encode  && docker-entrypoint -e"
#    volumes:
#      - ../docker/logstash-probateman/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
#      - ./../logstash:/usr/share/logstash/pipeline:ro
#    environment:
#      - DB_URL=jdbc:postgresql://probate-man-database:5432/probate_man
#      - DB_USER=probate_man
#      - DB_PWD=probate_man
#      - ES_DATA_NODES_URL=elasticsearch
#    depends_on:
#      - ccd-elasticsearch
#      - probate-man-database
#      - ccd-api-gateway
#      - ccd-definition-store-api
#      - ccd-case-management-web
#      - ccd-user-profile-api
#      - ccd-data-store-api

volumes:
  esdata1:
    driver: local

networks:
  compose_default:
    external: true

