package uk.gov.hmcts.probate.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>The Notice of Change challenge questions for {@code GrantOfRepresentation}.
 */
@Component
public class GrantOfRepresentationNoticeOfChange implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the Notice of Change challenge questions for {@code GrantOfRepresentation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.noticeOfChange()
            .challenge("NoCChallenge")
                .question("deceasedSurname", "Deceased Surname")
                .displayOrder(1)
                .answerFieldType("Text")
                .answer(UserRole.APPLICANTSOLICITOR)
                    .field("deceasedSurname")
                .done();
    }
}
