package uk.gov.hmcts.probate.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>The role-to-access-profile mappings for {@code GrantOfRepresentation}.
 */
@Component
public class GrantOfRepresentationRoleToAccessProfiles implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the role-to-access-profile mappings for {@code GrantOfRepresentation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.roleToAccessProfile("hmcts-admin")
            .accessProfiles("GS_profile")
            .readonly();
        builder.roleToAccessProfile("hmcts-judiciary")
            .accessProfiles("GS_profile")
            .readonly();
        builder.roleToAccessProfile("hmcts-legal-operations")
            .accessProfiles("GS_profile")
            .readonly();
        builder.roleToAccessProfile("hmcts-ctsc")
            .accessProfiles("GS_profile")
            .readonly();
        builder.roleToAccessProfile("specific-access-judiciary")
            .accessProfiles("GS_profile")
            .readonly();
        builder.roleToAccessProfile("specific-access-legal-ops")
            .accessProfiles("GS_profile")
            .readonly();
        builder.roleToAccessProfile("specific-access-admin")
            .accessProfiles("GS_profile")
            .readonly();
        builder.roleToAccessProfile("specific-access-ctsc")
            .accessProfiles("GS_profile")
            .readonly();
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .legacyIdamRole()
            .accessProfiles("caseworker-wa-task-configuration");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_CAA)
            .legacyIdamRole()
            .accessProfiles("caseworker-caa");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_APPROVER)
            .legacyIdamRole()
            .accessProfiles("caseworker-approver");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE_ISSUER)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate-issuer");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE_SOLICITOR)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate-solicitor");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE_SYSTEMUPDATE)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate-systemupdate")
            .accessProfiles("TTL_profile");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE_SCHEDULER)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate-scheduler")
            .accessProfiles("TTL_profile");
        builder.caseRoleToAccessProfile(UserRole.CITIZEN)
            .legacyIdamRole()
            .accessProfiles("citizen");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE_CASEADMIN)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate-caseadmin");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE_CASEOFFICER)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate-caseofficer");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE_REGISTRAR)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate-registrar");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE_SUPERUSER)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate-superuser");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE_PCQEXTRACTOR)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate-pcqextractor");
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE_CHARITY)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate-charity")
            .readonly();
        builder.caseRoleToAccessProfile(UserRole.CASEWORKER_PROBATE_RPAROBOT)
            .legacyIdamRole()
            .accessProfiles("caseworker-probate-rparobot");
        builder.roleToAccessProfile("cft-ttl-manager")
            .legacyIdamRole()
            .accessProfiles("TTL_profile");
        builder.caseRoleToAccessProfile(UserRole.CREATOR)
            .accessProfiles("[CREATOR]");
        builder.caseRoleToAccessProfile(UserRole.APPLICANTSOLICITOR)
            .accessProfiles("[APPLICANTSOLICITOR]");
    }
}
