package uk.gov.hmcts.probate.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>The work-basket input and result fields for {@code GrantOfRepresentation}.
 */
@Component
public class GrantOfRepresentationWorkBasket implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the work-basket input and result fields for {@code GrantOfRepresentation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.workBasketResultFields()
            .field("[CASE_REFERENCE]", "Case reference")
            .field("solsSolicitorAppReference", "Your reference")
            .field("deceasedForenames", "First name(s) of deceased")
            .field("deceasedSurname", "Last name(s) of deceased")
            .field("deceasedDateOfDeath", "Date of death")
            .field("registryLocation", "Registry Location")
            .field("applicationType", "Application Type")
            .field("evidenceHandled", "Supplementary evidence handled")
            .field("lastEvidenceAddedDate", "Date last evidence added");
    }
}
