package uk.gov.hmcts.probate.ccd;

import java.util.List;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.SearchPartyField;
import uk.gov.hmcts.ccd.sdk.api.SortOrder;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>The search input/result, search-cases, criteria and parties for {@code GrantOfRepresentation}.
 */
@Component
public class GrantOfRepresentationSearch implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the search input/result, search-cases, criteria and parties for {@code GrantOfRepresentation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.searchInputFields()
            .field("[CASE_REFERENCE]", "Case reference")
            .field("primaryApplicantForenames", "Applicant forename(s)")
            .field("primaryApplicantSurname", "Applicant surname(s)")
            .field("applicationSubmittedDate", "Application completed date")
            .field("grantIssuedDate", "Grant issued date")
            .field("applicationType", "Application type")
            .field("registryLocation", "Registry location")
            .field("[STATE]", "State")
            .field("deceasedForenames", "Deceased forename(s)")
            .field("deceasedSurname", "Deceased surname(s)")
            .field("deceasedDateOfBirth", "Deceased date of birth")
            .field("deceasedDateOfDeath", "Deceased date of death")
            .field("evidenceHandled", "Supplementary evidence handled")
            .field("caseType", "Case type")
            .field("latestGrantReissueDate", "Last grant reissue date")
            .field("caseHandedOffToLegacySite", "Case handed off to legacy site")
            .field("boHandoffReasonList", "Handoff reason")
            .field("registrarEscalateReason", "Escalation reason")
            .field("boCaseStopReasonList", "Case stop reason")
            .field("caseWorkerEscalationDate", "SME Referral Date")
            .field("resolveCaseWorkerEscalationDate", "SME Referral Resolved Date")
            .field("lastModifiedCaseworkerForenames", "Caseworker forename(s)")
            .field("lastModifiedCaseworkerSurname", "Caseworker surname(s)")
            .field("paymentTaken", "Payment taken");
        builder.searchResultFields()
            .field("[CASE_REFERENCE]", "Case reference")
            .field("primaryApplicantForenames", "Applicant forename(s)")
            .field("primaryApplicantSurname", "Applicant surname(s)")
            .field("deceasedForenames", "Deceased forename(s)")
            .field("deceasedSurname", "Deceased surname(s)")
            .field("deceasedDateOfDeath", "Date of death")
            .field("[STATE]", "State")
            .field("applicationSubmittedDate", "Application completed date", f -> f.resultsOrdering(SortOrder.FIRST.ASCENDING))
            .field("lastEvidenceAddedDate", "Date last evidence added")
            .field("grantIssuedDate", "Grant issued date")
            .field("[LAST_STATE_MODIFIED_DATE]", "Last State Modified Date");
        builder.searchCasesFields()
            .field("[CASE_REFERENCE]", "Case reference", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("solsSolicitorAppReference", "Your reference", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("primaryApplicantForenames", "Applicant Forename", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("primaryApplicantSurname", "Applicant Surname", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("deceasedForenames", "First name(s) of deceased", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("deceasedSurname", "Last name(s) of deceased", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("deceasedDateOfDeath", "Date of death", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("casePrinted", "Case printed", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("[STATE]", "State", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("applicationSubmittedDate", "Application completed date", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("evidenceHandled", "Supplementary evidence handled", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("grantIssuedDate", "Grant issued date", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"))
            .field("[LAST_STATE_MODIFIED_DATE]", "Last State Modified Date", f -> f.role(UserRole.CASEWORKER_CAA).useCase("ORGCASES"));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("deceasedForenames,deceasedSurname")
            .searchPartyDOB("deceasedDateOfBirth")
            .searchPartyDOD("deceasedDateOfDeath")
                    .build()));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("primaryApplicantForenames,primaryApplicantSurname")
            .searchPartyDOB("deceasedDateOfBirth")
            .searchPartyDOD("deceasedDateOfDeath")
                    .build()));
    }
}
