package uk.gov.hmcts.probate.model.ccd.raw;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import uk.gov.hmcts.probate.model.DocumentType;
import uk.gov.hmcts.reform.probate.model.ProbateDocument;
import uk.gov.hmcts.reform.probate.model.ProbateDocumentLink;
import uk.gov.hmcts.reform.probate.model.ProbateDocumentType;

import java.time.LocalDate;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.probate.model.ccd.raw.request.ProbateDocumentTypeEnum;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

@ComplexType(name = "ProbateDocument", generate = true)
@Data
@Builder
public class Document {

    @CCD(label = "Document Url", typeOverride = FieldType.Document)
    @JsonProperty("DocumentLink")
    private DocumentLink documentLink;

    @CCD(
            label = "Type",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "probateDocumentTypeEnum",
            typeParameterClass = ProbateDocumentTypeEnum.class
    )
    @JsonProperty("DocumentType")
    private DocumentType documentType;

    @CCD(label = "File name")
    @JsonProperty("DocumentFileName")
    private String documentFileName;

    @CCD(label = "Date added")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonProperty("DocumentDateAdded")
    private LocalDate documentDateAdded;

    @CCD(label = "Generated by")
    @JsonProperty("DocumentGeneratedBy")
    private String documentGeneratedBy;

    public Document() {
        super();
    }

    public Document(DocumentLink documentLink, DocumentType documentType, String documentFileName,
                    LocalDate documentDateAdded, String documentGeneratedBy) {
        this.documentLink = documentLink;
        this.documentType = documentType;
        this.documentFileName = documentFileName;
        this.documentDateAdded = documentDateAdded;
        this.documentGeneratedBy = documentGeneratedBy;
    }

    public ProbateDocument asProbateDocument() {
        ProbateDocumentLink probateDocumentLink = ProbateDocumentLink.builder()
                .documentBinaryUrl(getDocumentLink().getDocumentBinaryUrl())
                .documentFilename(getDocumentLink().getDocumentFilename())
                .documentUrl(getDocumentLink().getDocumentUrl())
                .build();
        ProbateDocumentType probateDocumentType = ProbateDocumentType.valueOf(getDocumentType().name());
        return ProbateDocument.builder()
                .documentDateAdded(getDocumentDateAdded())
                .documentFileName(getDocumentFileName())
                .documentGeneratedBy(getDocumentGeneratedBy())
                .documentLink(probateDocumentLink)
                .documentType(probateDocumentType)
                .build();

    }
}
