package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.ParagraphDetail;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code assembleLetterPage2} of event {@code assembleLetter}.
 */
public final class AssembleLetterAssembleLetterPage2Page {
    private AssembleLetterAssembleLetterPage2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("assembleLetterPage2");
        fields.mandatoryNoSummary(CaseData::getLetterText)
                    .fieldShowCondition("letterType=\"blank\"");
        fields.mandatoryNoSummary(CaseData::getCaseworkerName)
                    .fieldShowCondition("letterType=\"blank\"");
        fields.complex(CaseData::getParagraphDetails, false).done()
                    .fieldShowCondition("letterType=\"template\"");
        fields.complex(CaseData::getParagraphDetails, ParagraphDetail.class)
                    .readonly(ParagraphDetail::getEnableType)
                    .eventLabel(" ")
                    .readonly(ParagraphDetail::getLabel)
                    .eventLabel(" ")
                    .mandatory(ParagraphDetail::getTextValue)
                    .eventLabel(" ")
                    .optional(ParagraphDetail::getTextAreaValue)
                    .eventLabel(" ")
                    .mandatory(ParagraphDetail::getDynamicList)
                    .eventLabel(" ")
                    .mandatory(ParagraphDetail::getDateValue)
                    .eventLabel(" ").done();
    }
}
