package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage2B} of event {@code boAmendCaseDetailsForExamining}.
 */
public final class BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage2BPage {
    private BoAmendCaseDetailsForExaminingBoAmendCaseDetailsPage2BPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage2B");
        fields.showCondition("selectionList=\"deceasedIHT\"");
        fields.readonly(CaseData::getLabelIhtProbate);
        fields.mandatory(CaseData::getIhtGrossValue);
        fields.mandatory(CaseData::getIhtNetValue);
    }
}
