package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage5} of event {@code boAmendCaseDetailsForCaseQA}.
 */
public final class BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage5Page {
    private BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage5Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage5");
        fields.showCondition("selectionList=\"solicitor\"");
        fields.readonly(CaseData::getNotApplicableForThisCaseType1)
                    .fieldShowCondition("applicationType=\"Personal\"");
        fields.mandatory(CaseData::getSolsSOTForenames)
                    .fieldShowCondition("applicationType=\"Solicitor\"");
        fields.mandatory(CaseData::getSolsSOTSurname)
                    .fieldShowCondition("applicationType=\"Solicitor\"");
        fields.mandatory(CaseData::getSolsSolicitorIsExec)
                    .fieldShowCondition("applicationType=\"Solicitor\"");
        fields.mandatory(CaseData::getSolsSolicitorIsApplying)
                    .fieldShowCondition("applicationType=\"Solicitor\"");
        fields.mandatory(CaseData::getSolsSolicitorNotApplyingReason)
                    .fieldShowCondition("solsSolicitorIsApplying=\"No\" AND solsSolicitorIsExec=\"Yes\"");
        fields.mandatory(CaseData::getSolsSolicitorFirmName)
                    .fieldShowCondition("applicationType=\"Solicitor\"");
        fields.mandatory(CaseData::getSolsSolicitorAddress)
                    .fieldShowCondition("applicationType=\"Solicitor\"");
        fields.optional(CaseData::getSolsSolicitorEmail)
                    .fieldShowCondition("applicationType=\"Solicitor\"");
        fields.optional(CaseData::getSolsSolicitorPhoneNumber)
                    .fieldShowCondition("applicationType=\"Solicitor\"");
        fields.mandatory(CaseData::getSolsSolicitorAppReference)
                    .fieldShowCondition("applicationType=\"Solicitor\"");
    }
}
