package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage2A} of event {@code boAmendCaseDetailsForCaseMatchingExamining}.
 */
public final class BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage2APage {
    private BoAmendCaseDetailsForCaseMatchingExaminingBoAmendCaseDetailsPage2APage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage2A");
        fields.showCondition("selectionList=\"deceasedIHT\"");
        fields.mandatory(CaseData::getIhtFormEstateValuesCompleted)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\"");
        fields.mandatory(CaseData::getIhtFormEstate)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getLabelIhtEstate)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\"");
        fields.mandatory(CaseData::getIhtEstateGrossValue)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\"");
        fields.mandatory(CaseData::getIhtEstateNetValue)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\"");
        fields.mandatory(CaseData::getIhtEstateNetQualifyingValue)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\"");
        fields.mandatory(CaseData::getDeceasedHadLateSpouseOrCivilPartner)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\"");
        fields.optional(CaseData::getIhtUnusedAllowanceClaimed)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\"");
        fields.mandatory(CaseData::getIhtFormCompletedOnline)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"No\"");
        fields.optional(CaseData::getIhtReferenceNumber)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"No\" AND ihtFormCompletedOnline=\"Yes\"");
        fields.mandatory(CaseData::getIhtFormId)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"No\" AND ihtFormCompletedOnline=\"No\"")
                    .caseEventFieldLabel("Which Inheritance Tax (IHT) form was completed?");
        fields.mandatory(CaseData::getIht217)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"No\" AND ihtFormId=\"IHT205\"")
                    .caseEventFieldLabel("Did you complete the IHT217 to claim 100% unused nil-rate band?");
        fields.optional(CaseData::getForeignAsset)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"No\"");
        fields.optional(CaseData::getForeignAssetEstateValue)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"No\" AND foreignAsset=\"Yes\"");
    }
}
