package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage2B} of event {@code boAmendCaseDetailsForCaseStopped}.
 */
public final class BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage2BPage {
    private BoAmendCaseDetailsForCaseStoppedBoAmendCaseDetailsPage2BPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage2B");
        fields.showCondition("selectionList=\"deceasedIHT\"");
        fields.readonly(CaseData::getIhtNetValueSwitch)
                    .fieldShowCondition("[STATE]=\"NeverShow\"");
        fields.readonly(CaseData::getLabelIhtProbate)
                    .caseEventFieldLabel("### What are the values of the estate for probate?");
        fields.readonlyNoSummary(CaseData::getValueOfAssetSection1);
        fields.mandatory(CaseData::getIhtGrossValue);
        fields.mandatory(CaseData::getIhtNetValue)
                    .fieldShowCondition("applicationType=\"Personal\" OR (applicationType=\"Solicitor\" AND channelChoice=\"Digital\" AND ihtNetValueSwitch=\"Yes\") OR (applicationType=\"Solicitor\" AND channelChoice=\"PaperForm\") OR (applicationType=\"Solicitor\" AND channelChoice=\"BulkScan\")");
        fields.mandatory(CaseData::getIhtFormNetValue)
                    .fieldShowCondition("(applicationType=\"Solicitor\" AND channelChoice=\"Digital\" AND dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"Yes\" AND ihtFormEstate=\"IHT400\") OR (applicationType=\"Solicitor\" AND channelChoice=\"Digital\" AND dateOfDeathAfterEstateSwitch=\"No\" AND ihtFormId=\"IHT400\")");
    }
}
