package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage2} of event {@code boAmendCaseDetailsForReadyToIssue}.
 */
public final class BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage2Page {
    private BoAmendCaseDetailsForReadyToIssueBoAmendCaseDetailsPage2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage2");
        fields.showCondition("selectionList=\"deceasedIHT\"");
        fields.mandatory(CaseData::getDateOfDeathType);
        fields.mandatory(CaseData::getDeceasedDateOfBirth);
        fields.mandatory(CaseData::getDeceasedDateOfDeath);
        fields.optional(CaseData::getBoDeceasedTitle);
        fields.mandatory(CaseData::getDeceasedForenames);
        fields.mandatory(CaseData::getDeceasedSurname);
        fields.optional(CaseData::getBoDeceasedHonours);
        fields.mandatory(CaseData::getDeceasedAddress);
        fields.optional(CaseData::getSolsDeceasedAliasNamesList);
        fields.optional(CaseData::getDeceasedMaritalStatus);
    }
}
