package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage8} of event {@code boAmendCaseDetailsForReadyForExamination}.
 */
public final class BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage8Page {
    private BoAmendCaseDetailsForReadyForExaminationBoAmendCaseDetailsPage8Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage8");
        fields.showCondition("selectionList=\"domicility\"");
        fields.optional(CaseData::getDeceasedDomicileInEngWales);
        fields.mandatory(CaseData::getDomicilityCountry)
                    .fieldShowCondition("deceasedDomicileInEngWales=\"No\"");
        fields.optional(CaseData::getUkEstate);
        fields.optional(CaseData::getImmovableEstate);
        fields.readonly(CaseData::getImmovableEstateInfo)
                    .fieldShowCondition("immovableEstate=\"No\"");
        fields.optional(CaseData::getDeceasedHasAssetsOutsideUK)
                    .fieldShowCondition("caseType=\"intestacy\"");
        fields.optional(CaseData::getApplicationGrounds)
                    .fieldShowCondition("schemaVersion!=\"2.0.0\"");
        fields.optional(CaseData::getFurtherEvidenceForApplication);
        fields.optional(CaseData::getWillDispose)
                    .fieldShowCondition("caseType=\"gop\" AND applicationType=\"Solicitor\"");
        fields.optional(CaseData::getEnglishWill)
                    .fieldShowCondition("caseType=\"gop\" AND applicationType=\"Solicitor\"");
        fields.optional(CaseData::getAppointExec)
                    .fieldShowCondition("caseType=\"gop\" AND applicationType=\"Solicitor\" AND englishWill=\"Yes\"");
        fields.optional(CaseData::getAppointExecByDuties)
                    .fieldShowCondition("caseType=\"gop\" AND applicationType=\"Solicitor\" AND englishWill=\"No\"");
        fields.optional(CaseData::getAppointExecNo)
                    .fieldShowCondition("caseType=\"gop\" AND englishWill=\"Yes\" AND appointExec=\"No\"");
    }
}
