package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage9} of event {@code boAmendCaseDetailsForImport}.
 */
public final class BoAmendCaseDetailsForImportBoAmendCaseDetailsPage9Page {
    private BoAmendCaseDetailsForImportBoAmendCaseDetailsPage9Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage9");
        fields.showCondition("selectionList=\"deceasedFamily\"");
        fields.mandatory(CaseData::getSpouseOrPartner);
        fields.readonly(CaseData::getDeceasedRelativesLabel)
                    .fieldShowCondition("spouseOrPartner=\"No\"");
        fields.mandatory(CaseData::getChildrenSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\"");
        fields.optional(CaseData::getChildrenOverEighteenSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND childrenSurvived=\"Yes\"");
        fields.optional(CaseData::getChildrenUnderEighteenSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND childrenSurvived=\"Yes\"");
        fields.mandatory(CaseData::getChildrenDied)
                    .fieldShowCondition("spouseOrPartner=\"No\"");
        fields.optional(CaseData::getChildrenDiedOverEighteen)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND childrenDied=\"Yes\"");
        fields.optional(CaseData::getChildrenDiedUnderEighteen)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND childrenDied=\"Yes\"");
        fields.mandatory(CaseData::getGrandChildrenSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\"");
        fields.optional(CaseData::getGrandChildrenSurvivedOverEighteen)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND grandChildrenSurvived=\"Yes\"");
        fields.optional(CaseData::getGrandChildrenSurvivedUnderEighteen)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND grandChildrenSurvived=\"Yes\"");
        fields.mandatory(CaseData::getParentsExistSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getParentsExistOverEighteenSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND parentsExistSurvived=\"Yes\"");
        fields.optional(CaseData::getParentsExistUnderEighteenSurvived)
                    .fieldShowCondition("caseType=\"intestacy\"  AND parentsExistSurvived=\"Yes\"");
        fields.optional(CaseData::getWholeBloodSiblingsSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND caseType=\"intestacy\"");
        fields.optional(CaseData::getWholeBloodSiblingsSurvivedOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodSiblingsSurvived=\"Yes\"");
        fields.optional(CaseData::getWholeBloodSiblingsSurvivedUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodSiblingsSurvived=\"Yes\"");
        fields.mandatory(CaseData::getWholeBloodSiblingsDied)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getWholeBloodSiblingsDiedOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodSiblingsDied=\"Yes\"");
        fields.optional(CaseData::getWholeBloodSiblingsDiedUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodSiblingsDied=\"Yes\"");
        fields.mandatory(CaseData::getWholeBloodNeicesAndNephews)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getWholeBloodNeicesAndNephewsOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodNeicesAndNephews=\"Yes\"");
        fields.optional(CaseData::getWholeBloodNeicesAndNephewsUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodNeicesAndNephews=\"Yes\"");
        fields.mandatory(CaseData::getHalfBloodSiblingsSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getHalfBloodSiblingsSurvivedOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodSiblingsSurvived=\"Yes\"");
        fields.optional(CaseData::getHalfBloodSiblingsSurvivedUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodSiblingsSurvived=\"Yes\"");
        fields.mandatory(CaseData::getHalfBloodSiblingsDied)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getHalfBloodSiblingsDiedOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodSiblingsDied=\"Yes\"");
        fields.optional(CaseData::getHalfBloodSiblingsDiedUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodSiblingsDied=\"Yes\"");
        fields.mandatory(CaseData::getHalfBloodNeicesAndNephews)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getHalfBloodNeicesAndNephewsOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodNeicesAndNephews=\"Yes\"");
        fields.optional(CaseData::getHalfBloodNeicesAndNephewsUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodNeicesAndNephews=\"Yes\"");
        fields.mandatory(CaseData::getGrandparentsDied)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getGrandparentsDiedOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND grandparentsDied=\"Yes\"");
        fields.optional(CaseData::getGrandparentsDiedUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND grandparentsDied=\"Yes\"");
        fields.mandatory(CaseData::getWholeBloodUnclesAndAuntsSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getWholeBloodUnclesAndAuntsSurvivedOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodUnclesAndAuntsSurvived=\"Yes\"");
        fields.optional(CaseData::getWholeBloodUnclesAndAuntsSurvivedUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodUnclesAndAuntsSurvived=\"Yes\"");
        fields.mandatory(CaseData::getWholeBloodUnclesAndAuntsDied)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getWholeBloodUnclesAndAuntsDiedOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodUnclesAndAuntsDied=\"Yes\"");
        fields.optional(CaseData::getWholeBloodUnclesAndAuntsDiedUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodUnclesAndAuntsDied=\"Yes\"");
        fields.mandatory(CaseData::getWholeBloodCousinsSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getWholeBloodCousinsSurvivedOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodCousinsSurvived=\"Yes\"");
        fields.optional(CaseData::getWholeBloodCousinsSurvivedUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND wholeBloodCousinsSurvived=\"Yes\"");
        fields.mandatory(CaseData::getHalfBloodUnclesAndAuntsSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getHalfBloodUnclesAndAuntsSurvivedOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodUnclesAndAuntsSurvived=\"Yes\"");
        fields.optional(CaseData::getHalfBloodUnclesAndAuntsSurvivedUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodUnclesAndAuntsSurvived=\"Yes\"");
        fields.mandatory(CaseData::getHalfBloodUnclesAndAuntsDied)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getHalfBloodUnclesAndAuntsDiedOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodUnclesAndAuntsDied=\"Yes\"");
        fields.optional(CaseData::getHalfBloodUnclesAndAuntsDiedUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodUnclesAndAuntsDied=\"Yes\"");
        fields.mandatory(CaseData::getHalfBloodCousinsSurvived)
                    .fieldShowCondition("spouseOrPartner=\"No\" AND  caseType=\"intestacy\"");
        fields.optional(CaseData::getHalfBloodCousinsSurvivedOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodCousinsSurvived=\"Yes\"");
        fields.optional(CaseData::getHalfBloodCousinsSurvivedUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\" AND halfBloodCousinsSurvived=\"Yes\"");
        fields.optional(CaseData::getDeceasedSpouseNotApplyingReason)
                    .fieldShowCondition("caseType=\"intestacy\"");
        fields.optional(CaseData::getDeceasedDivorcedInEnglandOrWales)
                    .fieldShowCondition("caseType=\"intestacy\"");
        fields.optional(CaseData::getDeceasedOtherChildren)
                    .fieldShowCondition("caseType=\"intestacy\"");
        fields.optional(CaseData::getAllDeceasedChildrenOverEighteen)
                    .fieldShowCondition("caseType=\"intestacy\"");
        fields.optional(CaseData::getAnyDeceasedChildrenDieBeforeDeceased)
                    .fieldShowCondition("caseType=\"intestacy\"");
        fields.optional(CaseData::getAnyDeceasedGrandChildrenUnderEighteen)
                    .fieldShowCondition("caseType=\"intestacy\"");
        fields.optional(CaseData::getDeceasedAnyChildren)
                    .fieldShowCondition("caseType=\"intestacy\"");
    }
}
