package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage6} of event {@code boAmendCaseDetailsForCaseQA}.
 */
public final class BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage6Page {
    private BoAmendCaseDetailsForCaseQABoAmendCaseDetailsPage6Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage6");
        fields.showCondition("selectionList=\"attorney\"");
        fields.mandatory(CaseData::getApplyingAsAnAttorney);
        fields.optional(CaseData::getAttorneyOnBehalfOfNameAndAddress)
                    .fieldShowCondition("applyingAsAnAttorney=\"Yes\"");
        fields.optional(CaseData::getMentalCapacity)
                    .fieldShowCondition("applyingAsAnAttorney=\"Yes\"");
        fields.optional(CaseData::getCourtOfProtection)
                    .fieldShowCondition("applyingAsAnAttorney=\"Yes\"");
        fields.optional(CaseData::getEpaOrLpa)
                    .fieldShowCondition("applyingAsAnAttorney=\"Yes\"");
        fields.optional(CaseData::getEpaRegistered)
                    .fieldShowCondition("applyingAsAnAttorney=\"Yes\" AND epaOrLpa=\"Yes\"");
    }
}
