package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage7} of event {@code boAmendCaseDetailsPostGrantRegistrarEscalation}.
 */
public final class BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage7Page {
    private BoAmendCaseDetailsPostGrantRegistrarEscalationBoAmendCaseDetailsPage7Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage7");
        fields.showCondition("selectionList=\"willAndCodicils\"");
        fields.optional(CaseData::getWillExists);
        fields.optional(CaseData::getWillDatedBeforeApril);
        fields.optional(CaseData::getWillAccessOriginal)
                    .fieldShowCondition("willExists=\"Yes\"");
        fields.optional(CaseData::getWillAccessNotarial)
                    .fieldShowCondition("willAccessOriginal=\"No\"");
        fields.optional(CaseData::getOriginalWillSignedDate);
        fields.optional(CaseData::getWillHasCodicils)
                    .fieldShowCondition("willExists=\"Yes\"");
        fields.optional(CaseData::getCodicilAddedDateList)
                    .fieldShowCondition("willExists=\"Yes\" AND willHasCodicils=\"Yes\"");
        fields.optional(CaseData::getWillNumberOfCodicils)
                    .fieldShowCondition("schemaVersion!=\"2.0.0\" AND willExists=\"Yes\" AND willHasCodicils=\"Yes\"");
        fields.optional(CaseData::getWillsOutsideOfUK);
        fields.optional(CaseData::getDeceasedEnterMarriageOrCP);
        fields.optional(CaseData::getDateOfMarriageOrCP);
        fields.optional(CaseData::getDateOfDivorcedCPJudicially);
        fields.optional(CaseData::getCourtOfDecree);
        fields.optional(CaseData::getWillGiftUnderEighteen);
    }
}
