package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boExamineCaseReissueAmendDetailsPage1} of event {@code boExamineCaseReissueAmendDetails}.
 */
public final class BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage1Page {
    private BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage1Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boExamineCaseReissueAmendDetailsPage1");
        fields.optional(CaseData::getDateOfDeathAfterEstateSwitch)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.optional(CaseData::getSchemaVersion)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.mandatory(CaseData::getReissueSelectionList);
        fields.mandatory(CaseData::getChannelChoice);
        fields.mandatory(CaseData::getCaseType);
        fields.mandatory(CaseData::getApplicationType)
                    .caseEventFieldLabel("What application type is this?");
        fields.mandatory(CaseData::getRegistryLocation);
    }
}
