package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boExamineCaseReissueAmendDetailsPage4} of event {@code boExamineCaseReissueAmendDetails}.
 */
public final class BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage4Page {
    private BoExamineCaseReissueAmendDetailsBoExamineCaseReissueAmendDetailsPage4Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boExamineCaseReissueAmendDetailsPage4");
        fields.showCondition("reissueSelectionList=\"grant\"");
        fields.optional(CaseData::getBoWillMessage);
        fields.optional(CaseData::getBoExecutorLimitation);
        fields.optional(CaseData::getBoAdminClauseLimitation);
        fields.optional(CaseData::getBoLimitationText);
        fields.optional(CaseData::getExtraCopiesOfGrant);
        fields.optional(CaseData::getOutsideUKGrantCopies);
        fields.mandatory(CaseData::getCaseHandedOffToLegacySite);
    }
}
