package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.CaseLink;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.CaseMatch;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boFindMatchesStoppedReissuePage2} of event {@code boFindMatchedCaseForCaseStoppedReissue}.
 */
public final class BoFindMatchedCaseForCaseStoppedReissueBoFindMatchesStoppedReissuePage2Page {
    private BoFindMatchedCaseForCaseStoppedReissueBoFindMatchesStoppedReissuePage2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boFindMatchesStoppedReissuePage2");
        fields.complex(CaseData::getCaseMatches, false).done();
        fields.complex(CaseData::getCaseMatches, CaseMatch.class)
                    .readonly(CaseMatch::getType)
                    .eventLabel("Type")
                    .readonly(CaseMatch::getCcdCaseId)
                    .fieldShowCondition("legacyCaseViewUrl=\"NeverShowThisField\"")
                    .eventLabel("CCD Case No")
                    .readonly(CaseMatch::getFullName)
                    .eventLabel("Full name")
                    .readonly(CaseMatch::getDob)
                    .eventLabel("Date of birth")
                    .readonly(CaseMatch::getDod)
                    .eventLabel("Date of death")
                    .readonly(CaseMatch::getAliases)
                    .eventLabel("Aliases")
                    .readonly(CaseMatch::getPostcode)
                    .eventLabel("Postcode")
                    .optional(CaseMatch::getComment)
                    .eventLabel("Comment")
                    .readonly(CaseMatch::getCaseLink)
                    .eventLabel("Reference")
                    .complex(CaseMatch::getCaseLink)
                    .readonly(CaseLink::getCaseReference)
                    .eventLabel("CaseReference").done()
                    .readonly(CaseMatch::getRecordId)
                    .eventLabel("ProbateMan Id")
                    .readonly(CaseMatch::getId)
                    .eventLabel("Id")
                    .readonly(CaseMatch::getLegacyCaseViewUrl)
                    .eventLabel("Legacy case Url")
                    .optional(CaseMatch::getValid)
                    .eventLabel("Is match valid?")
                    .optional(CaseMatch::getDoImport)
                    .eventLabel("Do import?").done();
        fields.optional(CaseData::getMatches)
                    .fieldShowCondition("[STATE]=\"NeverShow\"");
    }
}
