package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boFindMatchesPage1} of event {@code boFindMatchedCasesForCases}.
 */
public final class BoFindMatchedCasesForCasesBoFindMatchesPage1Page {
    private BoFindMatchedCasesForCasesBoFindMatchesPage1Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boFindMatchesPage1");
        fields.showCondition("issueEarlySwitch=\"Yes\"");
        fields.optional(CaseData::getIssueEarlySwitch)
                    .fieldShowCondition("[STATE]=\"NeverShow\"");
        fields.optional(CaseData::getCaseType)
                    .fieldShowCondition("[STATE]=\"NeverShow\"");
        fields.readonly(CaseData::getIssueEarlyGopORAdmonWill)
                    .fieldShowCondition("caseType=\"gop\" OR caseType=\"admonWill\"");
        fields.readonly(CaseData::getIssueEarlyIntestacyORAdColligendaBona)
                    .fieldShowCondition("caseType=\"intestacy\" OR caseType=\"adColligendaBona\"");
    }
}
