package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage4} of event {@code boFullCaseAmendAwaitRedec}.
 */
public final class BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage4Page {
    private BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage4Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage4");
        fields.showCondition("applicationType=\"Solicitor\"");
        fields.mandatory(CaseData::getSolsSOTForenames);
        fields.mandatory(CaseData::getSolsSOTSurname);
        fields.mandatory(CaseData::getSolsSolicitorFirmName);
        fields.mandatory(CaseData::getSolsSolicitorAddress);
        fields.mandatory(CaseData::getSolsSolicitorAppReference);
        fields.optional(CaseData::getSolsSolicitorEmail);
        fields.optional(CaseData::getSolsSolicitorPhoneNumber);
        fields.optional(CaseData::getSolsSOTJobTitle);
    }
}
