package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage1} of event {@code boFullCaseAmend}.
 */
public final class BoFullCaseAmendBoAmendCaseDetailsPage1Page {
    private BoFullCaseAmendBoAmendCaseDetailsPage1Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage1");
        fields.optional(CaseData::getSchemaVersion)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.mandatory(CaseData::getChannelChoice);
        fields.mandatory(CaseData::getLanguagePreferenceWelsh);
        fields.mandatory(CaseData::getCaseType);
        fields.mandatory(CaseData::getApplicationType)
                    .caseEventFieldLabel("What application type is this?");
        fields.mandatory(CaseData::getRegistryLocation);
        fields.mandatory(CaseData::getDateOfDeathType);
        fields.mandatory(CaseData::getDeceasedDateOfBirth);
        fields.mandatory(CaseData::getDeceasedDateOfDeath);
        fields.optional(CaseData::getBoDeceasedTitle);
        fields.mandatory(CaseData::getDeceasedForenames);
        fields.mandatory(CaseData::getDeceasedSurname);
        fields.optional(CaseData::getBoDeceasedHonours);
        fields.mandatory(CaseData::getDeceasedAddress);
        fields.optional(CaseData::getSolsDeceasedAliasNamesList);
        fields.optional(CaseData::getDeceasedMaritalStatus);
        fields.mandatory(CaseData::getIhtFormCompletedOnline);
        fields.optional(CaseData::getIhtReferenceNumber)
                    .fieldShowCondition("ihtFormCompletedOnline=\"Yes\"");
        fields.mandatory(CaseData::getIhtFormId)
                    .fieldShowCondition("ihtFormCompletedOnline=\"No\"");
        fields.mandatory(CaseData::getIhtGrossValue);
        fields.mandatory(CaseData::getIhtNetValue);
        fields.mandatory(CaseData::getIht217)
                    .fieldShowCondition("ihtFormId=\"IHT205\"")
                    .caseEventFieldLabel("Did you complete the IHT217 to claim 100% unused nil-rate band?");
        fields.optional(CaseData::getForeignAsset);
        fields.optional(CaseData::getForeignAssetEstateValue)
                    .fieldShowCondition("foreignAsset=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getBulkScanCaseReference);
        fields.mandatory(CaseData::getSolsSolicitorIsExec)
                    .fieldShowCondition("applicationType=\"Solicitor\"");
        fields.mandatory(CaseData::getSolsSolicitorIsApplying)
                    .fieldShowCondition("applicationType=\"Solicitor\"");
        fields.mandatory(CaseData::getSolsSolicitorNotApplyingReason)
                    .fieldShowCondition("solsSolicitorIsApplying=\"No\" AND solsSolicitorIsExec=\"Yes\"");
    }
}
