package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boAmendCaseDetailsPage2} of event {@code boFullCaseAmendAwaitRedec}.
 */
public final class BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage2Page {
    private BoFullCaseAmendAwaitRedecBoAmendCaseDetailsPage2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boAmendCaseDetailsPage2");
        fields.optional(CaseData::getPrimaryApplicantForenames);
        fields.optional(CaseData::getPrimaryApplicantSurname);
        fields.optional(CaseData::getPrimaryApplicantAlias);
        fields.optional(CaseData::getPrimaryApplicantAliasReason);
        fields.optional(CaseData::getPrimaryApplicantOtherReason)
                    .fieldShowCondition("primaryApplicantAliasReason=\"other\"");
        fields.optional(CaseData::getPrimaryApplicantRelationshipToDeceased)
                    .fieldShowCondition("applicationType=\"Personal\" AND caseType=\"intestacy\" OR (applicationType=\"Solicitor\" AND caseType=\"intestacy\" AND channelChoice=\"PaperForm\") OR (applicationType=\"Solicitor\" AND caseType=\"intestacy\" AND channelChoice=\"BulkScan\")");
        fields.optional(CaseData::getPaRelationshipToDeceasedOther)
                    .fieldShowCondition("primaryApplicantRelationshipToDeceased=\"other\"");
        fields.optional(CaseData::getSolsApplicantRelationshipToDeceased)
                    .fieldShowCondition("applicationType=\"Solicitor\" AND caseType=\"intestacy\" AND channelChoice=\"Digital\"");
        fields.optional(CaseData::getPrimaryApplicantPhoneNumber);
        fields.optional(CaseData::getPrimaryApplicantSecondPhoneNumber);
        fields.optional(CaseData::getPrimaryApplicantEmailAddress);
        fields.optional(CaseData::getPrimaryApplicantIsApplying);
        fields.mandatory(CaseData::getSolsPrimaryExecutorNotApplyingReason)
                    .fieldShowCondition("primaryApplicantIsApplying=\"No\"");
        fields.mandatory(CaseData::getPrimaryApplicantAddress)
                    .fieldShowCondition("primaryApplicantIsApplying=\"Yes\"");
        fields.optional(CaseData::getAdditionalExecutorsApplying);
        fields.optional(CaseData::getAdditionalExecutorsNotApplying);
        fields.optional(CaseData::getNotifiedApplicants);
        fields.optional(CaseData::getEntitledToApply);
        fields.optional(CaseData::getEntitledToApplyOther)
                    .fieldShowCondition("entitledToApply=\"Yes\"");
        fields.optional(CaseData::getPrimaryApplicantAdoptionInEnglandOrWales)
                    .fieldShowCondition("caseType=\"intestacy\"");
    }
}
