package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code issueGrantPage1} of event {@code boIssueGrantForCaseMatching}.
 */
public final class BoIssueGrantForCaseMatchingIssueGrantPage1Page {
    private BoIssueGrantForCaseMatchingIssueGrantPage1Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("issueGrantPage1");
        fields.showCondition("hasValidMatches=\"Yes\"");
        fields.optionalNoSummary(CaseData::getHasValidMatches)
                    .fieldShowCondition("[STATE]=\"NeverShow\"");
        fields.readonlyNoSummary(CaseData::getHasValidMatchesLabel);
    }
}
