package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ExecutorsApplyingNotification;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boNotifyRedeclarationSOTPage2} of event {@code boNotifyRedeclarationSOT}.
 */
public final class BoNotifyRedeclarationSOTBoNotifyRedeclarationSOTPage2Page {
    private BoNotifyRedeclarationSOTBoNotifyRedeclarationSOTPage2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boNotifyRedeclarationSOTPage2");
        fields.complex(CaseData::getExecutorsApplyingNotifications).done();
        fields.complex(CaseData::getExecutorsApplyingNotifications, ExecutorsApplyingNotification.class)
                    .readonly(ExecutorsApplyingNotification::getName)
                    .eventLabel("Name of the executor")
                    .readonly(ExecutorsApplyingNotification::getEmail)
                    .fieldShowCondition("name=\"NeverShowThisField\"")
                    .eventLabel("Email of the executor")
                    .readonly(ExecutorsApplyingNotification::getAddress)
                    .fieldShowCondition("name=\"NeverShowThisField\"")
                    .eventLabel("Address of the executor")
                    .mandatory(ExecutorsApplyingNotification::getNotification)
                    .eventLabel("Do you wish to send a notification?")
                    .mandatory(ExecutorsApplyingNotification::getResponseReceived)
                    .fieldShowCondition("name=\"NeverShowThisField\"")
                    .eventLabel("Has a response been received?").done();
    }
}
