package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code boRequestInfoForCaseStoppedPage1} of event {@code boRequestInfoForCaseStopped}.
 */
public final class BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage1Page {
    private BoRequestInfoForCaseStoppedBoRequestInfoForCaseStoppedPage1Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("boRequestInfoForCaseStoppedPage1");
        fields.showCondition("(applicationType=\"Personal\" AND primaryApplicantEmailAddress=\"\") OR (applicationType=\"Solicitor\" AND solsSolicitorEmail=\"\")");
        fields.optional(CaseData::getApplicationType)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.optional(CaseData::getPrimaryApplicantEmailAddress)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.optional(CaseData::getSolsSolicitorEmail)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.optional(CaseData::getChannelChoice)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.readonly(CaseData::getInformationNeededByPostSwitch)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.readonlyNoSummary(CaseData::getUseAssembleLetterEvent);
    }
}
