package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.caseaccess.Organisation;
import uk.gov.hmcts.probate.model.caseaccess.OrganisationPolicy;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorCreateApplicationPage2} of event {@code solicitorCreateApplication}.
 */
public final class SolicitorCreateApplicationSolicitorCreateApplicationPage2Page {
    private SolicitorCreateApplicationSolicitorCreateApplicationPage2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorCreateApplicationPage2");
        fields.readonlyNoSummary(CaseData::getSolsApplyPage);
        fields.readonlyNoSummary(CaseData::getSolsPractitionerDtlsHelp);
        fields.mandatory(CaseData::getSolsSolicitorWillSignSOT);
        fields.mandatory(CaseData::getSolsForenames)
                    .fieldShowCondition("solsSolicitorWillSignSOT=\"No\"");
        fields.mandatory(CaseData::getSolsSurname)
                    .fieldShowCondition("solsSolicitorWillSignSOT=\"No\"");
        fields.mandatory(CaseData::getSolsSOTForenames);
        fields.mandatory(CaseData::getSolsSOTSurname);
        fields.mandatory(CaseData::getSolsSolicitorIsExec);
        fields.readonlyNoSummary(CaseData::getApplyForProbatePageHint1)
                    .fieldShowCondition("solsSolicitorIsExec=\"Yes\"");
        fields.mandatory(CaseData::getSolsSolicitorIsApplying);
        fields.readonlyNoSummary(CaseData::getApplyForProbatePageHint2)
                    .fieldShowCondition("solsSolicitorIsExec=\"No\" AND solsSolicitorIsApplying=\"Yes\"");
        fields.mandatory(CaseData::getSolsSolicitorNotApplyingReason)
                    .fieldShowCondition("solsSolicitorIsApplying=\"No\" AND solsSolicitorIsExec=\"Yes\"")
                    .retainHiddenValue();
        fields.mandatory(CaseData::getSolsSolicitorFirmName);
        fields.mandatory(CaseData::getSolsSolicitorAddress);
        fields.mandatory(CaseData::getSolsSolicitorEmail);
        fields.optional(CaseData::getSolsSolicitorPhoneNumber);
        fields.mandatory(CaseData::getSolsSolicitorAppReference);
        fields.complex(CaseData::getApplicantOrganisationPolicy)
                    .optional(OrganisationPolicy::getOrgPolicyCaseAssignedRole)
                    .fieldShowCondition("name=\"NeverShowThisField\"")
                    .optional(OrganisationPolicy::getOrgPolicyReference)
                    .fieldShowCondition("name=\"NeverShowThisField\"")
                    .complex(OrganisationPolicy::getOrganisation)
                    .optional(Organisation::getOrganisationID)
                    .fieldShowCondition("name=\"NeverShowThisField\"").done()
                    .complex(OrganisationPolicy::getOrganisation)
                    .optional(Organisation::getOrganisationName)
                    .fieldShowCondition("name=\"NeverShowThisField\"").done().done()
                    .fieldShowCondition("[STATE]=\"NeverShowThisField\"")
                    .retainHiddenValue();
    }
}
