package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateAdmonPage3} of event {@code solicitorUpdateAdmon}.
 */
public final class SolicitorUpdateAdmonSolicitorUpdateAdmonPage3Page {
    private SolicitorUpdateAdmonSolicitorUpdateAdmonPage3Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateAdmonPage3");
        fields.pageLabel("About the applicant");
        fields.mandatory(CaseData::getSolsEntitledMinority);
        fields.readonly(CaseData::getSolsEntitledMinorityInfo)
                    .fieldShowCondition("solsEntitledMinority=\"Yes\"");
        fields.mandatory(CaseData::getDeceasedDomicileInEngWales)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.mandatory(CaseData::getImmovableEstate)
                    .fieldShowCondition("deceasedDomicileInEngWales=\"No\"");
        fields.readonlyNoSummary(CaseData::getImmovableEstateInfo)
                    .fieldShowCondition("immovableEstate=\"No\"");
        fields.mandatory(CaseData::getSolsDiedOrNotApplying);
        fields.readonly(CaseData::getSolsDiedOrNotApplyingInfo)
                    .fieldShowCondition("solsDiedOrNotApplying=\"No\"");
        fields.mandatory(CaseData::getSolsResiduary);
        fields.readonly(CaseData::getSolsResiduaryInfo)
                    .fieldShowCondition("solsResiduary=\"No\"");
        fields.mandatory(CaseData::getSolsResiduaryType)
                    .fieldShowCondition("solsResiduary=\"Yes\"");
        fields.mandatory(CaseData::getSolsLifeInterest);
        fields.readonly(CaseData::getSolsLifeInterestInfo)
                    .fieldShowCondition("solsLifeInterest=\"Yes\"");
    }
}
