package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateApplicationPage5} of event {@code solicitorUpdateApplication}.
 */
public final class SolicitorUpdateApplicationSolicitorUpdateApplicationPage5Page {
    private SolicitorUpdateApplicationSolicitorUpdateApplicationPage5Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateApplicationPage5");
        fields.pageLabel("HMRC code");
        fields.showCondition("(dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"Yes\" AND ihtFormEstate=\"IHT400\" AND hmrcLetterId=\"No\") OR (dateOfDeathAfterEstateSwitch=\"No\" AND ihtFormId=\"IHT400\" AND hmrcLetterId=\"No\")");
        fields.readonlyNoSummary(CaseData::getIht400Wait);
    }
}
