package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateApplicationPage8} of event {@code solicitorUpdateApplication}.
 */
public final class SolicitorUpdateApplicationSolicitorUpdateApplicationPage8Page {
    private SolicitorUpdateApplicationSolicitorUpdateApplicationPage8Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateApplicationPage8");
        fields.pageLabel("Information about the will");
        fields.showCondition("(ihtGrossValue!=\"\" AND ihtNetValue!=\"\" AND solsWillType=\"WillLeft\" AND iht400Switch=\"Yes\") OR (ihtGrossValue!=\"\" AND ihtFormNetValue!=\"\" AND solsWillType=\"WillLeft\" AND iht400Switch=\"Yes\")");
        fields.mandatory(CaseData::getWillDispose);
        fields.readonlyNoSummary(CaseData::getNoProofEntitlement)
                    .fieldShowCondition("willDispose=\"No\"");
        fields.mandatory(CaseData::getEnglishWill);
        fields.readonly(CaseData::getEnglishWillNo)
                    .fieldShowCondition("englishWill=\"No\"");
        fields.mandatory(CaseData::getAppointExec)
                    .fieldShowCondition("englishWill=\"Yes\"");
        fields.mandatory(CaseData::getAppointExecByDuties)
                    .fieldShowCondition("englishWill=\"No\"");
        fields.mandatory(CaseData::getAppointExecNo)
                    .fieldShowCondition("englishWill=\"Yes\" AND appointExec=\"No\"");
    }
}
