package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorConfirmPage4} of event {@code solicitorReviewAndConfirm}.
 */
public final class SolicitorReviewAndConfirmSolicitorConfirmPage4Page {
    private SolicitorReviewAndConfirmSolicitorConfirmPage4Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorConfirmPage4");
        fields.showCondition("solsSOTNeedToUpdate=\"Yes\"");
        fields.mandatoryNoSummary(CaseData::getSolsAmendLegalStatmentSelect);
        fields.readonlyNoSummary(CaseData::getSolsAmendLegalStatmentInfo);
    }
}
