package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorReviewLegalStatementPage1} of event {@code solicitorReviewAndConfirm}.
 */
public final class SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage1Page {
    private SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage1Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorReviewLegalStatementPage1");
        fields.pageLabel("Review legal statement and declaration");
        fields.readonlyNoSummary(CaseData::getSolsReviewLegalStatement1);
        fields.readonlyNoSummary(CaseData::getSolsReviewLegalStatement2);
        fields.readonlyNoSummary(CaseData::getSolsReviewLegalStatement3);
        fields.readonlyNoSummary(CaseData::getSolsReviewLegalStatement4);
        fields.readonlyNoSummary(CaseData::getSolsReviewLegalStatement5);
        fields.readonlyNoSummary(CaseData::getSolsLegalStatementDocument);
        fields.mandatoryNoSummary(CaseData::getSolsSOTNeedToUpdate);
    }
}
