package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateProbatePage2} of event {@code solicitorUpdateProbate}.
 */
public final class SolicitorUpdateProbateSolicitorUpdateProbatePage2Page {
    private SolicitorUpdateProbateSolicitorUpdateProbatePage2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateProbatePage2");
        fields.mandatory(CaseData::getDispenseWithNotice);
        fields.mandatory(CaseData::getTitleAndClearingType);
        fields.mandatory(CaseData::getNameOfFirmNamedInWill)
                    .fieldShowCondition("titleAndClearingType=\"TCTPartSuccPowerRes\" OR titleAndClearingType=\"TCTPartPowerRes\" OR titleAndClearingType=\"TCTSolePrinSucc\" OR titleAndClearingType=\"TCTSolePrin\" OR titleAndClearingType=\"TCTPartSuccAllRenouncing\" OR titleAndClearingType=\"TCTPartAllRenouncing\" OR titleAndClearingType=\"TCTPartSuccOthersRenouncing\" OR titleAndClearingType=\"TCTPartOthersRenouncing\" OR titleAndClearingType=\"TCTFirmCeasedTradingNoSucc\"");
        fields.mandatory(CaseData::getAddressOfFirmNamedInWill)
                    .fieldShowCondition("titleAndClearingType=\"TCTPartPowerRes\" OR titleAndClearingType=\"TCTSolePrin\" OR titleAndClearingType=\"TCTPartOthersRenouncing\"");
        fields.mandatory(CaseData::getNameOfSucceededFirm)
                    .fieldShowCondition("titleAndClearingType=\"TCTPartSuccPowerRes\" OR titleAndClearingType=\"TCTSolePrinSucc\" OR titleAndClearingType=\"TCTPartSuccAllRenouncing\" OR titleAndClearingType=\"TCTPartSuccOthersRenouncing\"");
        fields.mandatory(CaseData::getAddressOfSucceededFirm)
                    .fieldShowCondition("titleAndClearingType=\"TCTPartSuccPowerRes\" OR titleAndClearingType=\"TCTSolePrinSucc\" OR titleAndClearingType=\"TCTPartSuccOthersRenouncing\"");
        fields.mandatory(CaseData::getTrustCorpName)
                    .fieldShowCondition("titleAndClearingType=\"TCTTrustCorpResWithSDJ\" OR titleAndClearingType=\"TCTTrustCorpResWithApp\"");
        fields.mandatory(CaseData::getTrustCorpAddress)
                    .fieldShowCondition("titleAndClearingType=\"TCTTrustCorpResWithSDJ\" OR titleAndClearingType=\"TCTTrustCorpResWithApp\"");
        fields.readonlyNoSummary(CaseData::getSolsPreviouslyIdentifiedExecsCcdCopy)
                    .fieldShowCondition("solsSolicitorIsExec=\"Yes\" OR solsSolicitorIsApplying=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getSolsIdentifiedApplyingExecsCcdCopy)
                    .fieldShowCondition("solsSolicitorIsExec=\"Yes\" OR solsSolicitorIsApplying=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getSolsIdentifiedNotApplyingExecsCcdCopy)
                    .fieldShowCondition("solsSolicitorIsExec=\"Yes\" OR solsSolicitorIsApplying=\"Yes\"");
        fields.mandatory(CaseData::getAnyOtherApplyingPartners)
                    .fieldShowCondition("titleAndClearingType=\"TCTPartSuccPowerRes\" OR titleAndClearingType=\"TCTPartPowerRes\" OR titleAndClearingType=\"TCTSolePrinSucc\" OR titleAndClearingType=\"TCTSolePrin\" OR titleAndClearingType=\"TCTPartSuccOthersRenouncing\" OR titleAndClearingType=\"TCTPartOthersRenouncing\"");
        fields.mandatory(CaseData::getOtherPartnersApplyingAsExecutors)
                    .fieldShowCondition("(titleAndClearingType=\"TCTPartSuccPowerRes\" OR titleAndClearingType=\"TCTPartPowerRes\" OR titleAndClearingType=\"TCTSolePrinSucc\" OR titleAndClearingType=\"TCTSolePrin\" OR titleAndClearingType=\"TCTPartSuccOthersRenouncing\" OR titleAndClearingType=\"TCTPartOthersRenouncing\") AND anyOtherApplyingPartners=\"Yes\"");
        fields.mandatory(CaseData::getMorePartnersHoldingPowerReserved)
                    .fieldShowCondition("titleAndClearingType=\"TCTPartSuccPowerRes\" OR titleAndClearingType=\"TCTPartPowerRes\"");
        fields.optional(CaseData::getProbatePractitionersPositionInTrust)
                    .fieldShowCondition("titleAndClearingType=\"TCTTrustCorpResWithSDJ\" OR titleAndClearingType=\"TCTTrustCorpResWithApp\"");
        fields.mandatory(CaseData::getAnyOtherApplyingPartnersTrustCorp)
                    .fieldShowCondition("titleAndClearingType=\"TCTTrustCorpResWithSDJ\" OR titleAndClearingType=\"TCTTrustCorpResWithApp\"");
        fields.mandatory(CaseData::getAdditionalExecutorsTrustCorpList)
                    .fieldShowCondition("(titleAndClearingType=\"TCTTrustCorpResWithSDJ\" OR titleAndClearingType=\"TCTTrustCorpResWithApp\") AND anyOtherApplyingPartnersTrustCorp=\"Yes\"");
        fields.optional(CaseData::getLodgementAddress)
                    .fieldShowCondition("titleAndClearingType=\"TCTTrustCorpResWithSDJ\"");
        fields.mandatory(CaseData::getLodgementDate)
                    .fieldShowCondition("titleAndClearingType=\"TCTTrustCorpResWithSDJ\"");
        fields.mandatory(CaseData::getWhoSharesInCompanyProfits)
                    .fieldShowCondition("titleAndClearingType=\"TCTSolePrinSucc\" OR titleAndClearingType=\"TCTSolePrin\" OR titleAndClearingType=\"TCTPartSuccPowerRes\" OR titleAndClearingType=\"TCTPartPowerRes\" OR titleAndClearingType=\"TCTPartSuccAllRenouncing\" OR titleAndClearingType=\"TCTPartAllRenouncing\" OR titleAndClearingType=\"TCTPartSuccOthersRenouncing\" OR titleAndClearingType=\"TCTPartOthersRenouncing\"");
        fields.readonlyNoSummary(CaseData::getNoneOfTheseOptionStop)
                    .fieldShowCondition("solsSolicitorIsExec=\"No\" AND solsSolicitorIsApplying=\"Yes\" AND titleAndClearingType=\"TCTNoT\"");
        fields.readonlyNoSummary(CaseData::getNoneOfTheseOptionNoNo)
                    .fieldShowCondition("solsSolicitorIsExec=\"No\" AND solsSolicitorIsApplying=\"No\" AND titleAndClearingType=\"TCTNoT\"");
        fields.readonlyNoSummary(CaseData::getNoneOfTheseOptionYesYes)
                    .fieldShowCondition("solsSolicitorIsExec=\"Yes\" AND solsSolicitorIsApplying=\"Yes\" AND titleAndClearingType=\"TCTNoT\"");
        fields.readonlyNoSummary(CaseData::getNoneOfTheseOptionYesNo)
                    .fieldShowCondition("solsSolicitorIsExec=\"Yes\" AND solsSolicitorIsApplying=\"No\" AND titleAndClearingType=\"TCTNoT\"");
    }
}
