package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateAdmonPage4} of event {@code solicitorUpdateAdmon}.
 */
public final class SolicitorUpdateAdmonSolicitorUpdateAdmonPage4Page {
    private SolicitorUpdateAdmonSolicitorUpdateAdmonPage4Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateAdmonPage4");
        fields.mandatory(CaseData::getFurtherEvidenceForApplication)
                    .caseEventFieldHint("Where there is a will, this could include rule 12 (3) clearing, explanation of the plight and condition of the will, information supporting the will’s validity or information on any other documents of a testamentary nature that may exist. You may also wish to provide information to confirm the identity of an executor or beneficiary. You must account for executors not applying here and give details as to why they are not applying.");
    }
}
