package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateApplicationPage6} of event {@code solicitorUpdateApplication}.
 */
public final class SolicitorUpdateApplicationSolicitorUpdateApplicationPage6Page {
    private SolicitorUpdateApplicationSolicitorUpdateApplicationPage6Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateApplicationPage6");
        fields.pageLabel("Value of assets for Probate");
        fields.showCondition("iht400Switch=\"Yes\"");
        fields.readonly(CaseData::getIht400Switch)
                    .fieldShowCondition("[STATE]=\"NeverShow\"");
        fields.readonly(CaseData::getIhtNetValueSwitch)
                    .fieldShowCondition("[STATE]=\"NeverShow\"");
        fields.readonlyNoSummary(CaseData::getValueOfAssetSection2)
                    .fieldShowCondition("(dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"Yes\" AND ihtFormEstate=\"IHT400\" AND hmrcLetterId=\"Yes\") OR (dateOfDeathAfterEstateSwitch=\"No\" AND ihtFormId=\"IHT400\" AND hmrcLetterId=\"Yes\")");
        fields.readonlyNoSummary(CaseData::getValueOfAssetSection1);
        fields.mandatory(CaseData::getIhtGrossValue)
                    .caseEventFieldLabel("What is the gross value of assets for probate?");
        fields.mandatory(CaseData::getIhtNetValue)
                    .fieldShowCondition("ihtNetValueSwitch=\"Yes\"")
                    .caseEventFieldLabel("What is the net value of the estate for probate?");
        fields.mandatory(CaseData::getIhtFormNetValue)
                    .fieldShowCondition("(dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"Yes\" AND ihtFormEstate=\"IHT400\" AND hmrcLetterId=\"Yes\") OR (dateOfDeathAfterEstateSwitch=\"No\" AND ihtFormId=\"IHT400\" AND hmrcLetterId=\"Yes\")")
                    .caseEventFieldLabel("What is the net value for probate?");
    }
}
