package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorReviewLegalStatementPage2} of event {@code solicitorReviewAndConfirm}.
 */
public final class SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage2Page {
    private SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorReviewLegalStatementPage2");
        fields.pageLabel("Inheritance tax forms");
        fields.showCondition("showIht400421Page=\"Yes\" AND solsSOTNeedToUpdate=\"No\"");
        fields.mandatoryNoSummary(CaseData::getShowIht400421Page)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.mandatoryNoSummary(CaseData::getSolsIHT400Date);
    }
}
