package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateApplicationPage3} of event {@code solicitorUpdateApplication}.
 */
public final class SolicitorUpdateApplicationSolicitorUpdateApplicationPage3Page {
    private SolicitorUpdateApplicationSolicitorUpdateApplicationPage3Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateApplicationPage3");
        fields.pageLabel("Inheritance Tax");
        fields.showCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\"");
        fields.mandatory(CaseData::getDeceasedHadLateSpouseOrCivilPartner)
                    .caseEventFieldLabel("Did the deceased have a late husband, wife or civil partner?");
        fields.mandatory(CaseData::getIhtUnusedAllowanceClaimed)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\" AND deceasedHadLateSpouseOrCivilPartner=\"Yes\"");
    }
}
