package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorReviewLegalStatementPage3} of event {@code solicitorReviewAndConfirm}.
 */
public final class SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage3Page {
    private SolicitorReviewAndConfirmSolicitorReviewLegalStatementPage3Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorReviewLegalStatementPage3");
        fields.pageLabel("Upload legal statement");
        fields.showCondition("solsSOTNeedToUpdate=\"No\"");
        fields.readonlyNoSummary(CaseData::getSolsLegalStatementUploadLabel1);
        fields.readonlyNoSummary(CaseData::getSolsLegalStatementUploadLabel2);
        fields.readonlyNoSummary(CaseData::getSolsLegalStatementUploadLabel3);
        fields.readonlyNoSummary(CaseData::getSolsLegalStatementUploadLabel4);
        fields.readonlyNoSummary(CaseData::getSolsLegalStatementUploadLabel5);
        fields.readonlyNoSummary(CaseData::getSolsLegalStatementUploadLabel6);
        fields.optional(CaseData::getSolsLegalStatementUpload);
    }
}
