package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateAppSolDtlsPage2} of event {@code solicitorUpdateAppSolDtls}.
 */
public final class SolicitorUpdateAppSolDtlsSolicitorUpdateAppSolDtlsPage2Page {
    private SolicitorUpdateAppSolDtlsSolicitorUpdateAppSolDtlsPage2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateAppSolDtlsPage2");
        fields.readonlyNoSummary(CaseData::getSolsApplyPage);
        fields.readonlyNoSummary(CaseData::getSolsPractitionerDtlsHelp);
        fields.mandatory(CaseData::getSolsSolicitorWillSignSOT);
        fields.mandatory(CaseData::getSolsForenames)
                    .fieldShowCondition("solsSolicitorWillSignSOT=\"No\"");
        fields.mandatory(CaseData::getSolsSurname)
                    .fieldShowCondition("solsSolicitorWillSignSOT=\"No\"");
        fields.mandatory(CaseData::getSolsSOTForenames);
        fields.mandatory(CaseData::getSolsSOTSurname);
        fields.mandatory(CaseData::getSolsSolicitorIsExec);
        fields.mandatory(CaseData::getSolsSolicitorIsApplying);
        fields.mandatory(CaseData::getSolsSolicitorNotApplyingReason)
                    .fieldShowCondition("solsSolicitorIsApplying=\"No\" AND solsSolicitorIsExec=\"Yes\"")
                    .retainHiddenValue();
        fields.mandatory(CaseData::getSolsSolicitorFirmName);
        fields.mandatory(CaseData::getSolsSolicitorAddress);
        fields.mandatory(CaseData::getSolsSolicitorEmail);
        fields.optional(CaseData::getSolsSolicitorPhoneNumber);
        fields.mandatory(CaseData::getSolsSolicitorAppReference);
    }
}
