package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateProbatePage1} of event {@code solicitorUpdateProbate}.
 */
public final class SolicitorUpdateProbateSolicitorUpdateProbatePage1Page {
    private SolicitorUpdateProbateSolicitorUpdateProbatePage1Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateProbatePage1");
        fields.readonly(CaseData::getSolsSolicitorIsApplying)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.mandatory(CaseData::getWillAccessOriginal);
        fields.mandatory(CaseData::getWillAccessNotarial)
                    .fieldShowCondition("willAccessOriginal=\"No\"");
        fields.readonlyNoSummary(CaseData::getWillAccessOriginalHintText)
                    .fieldShowCondition("willAccessOriginal=\"No\" AND willAccessNotarial=\"No\"");
        fields.readonlyNoSummary(CaseData::getWillAccessNotarialYesLabel)
                    .fieldShowCondition("willAccessOriginal=\"No\" AND willAccessNotarial=\"Yes\"");
        fields.mandatory(CaseData::getOriginalWillSignedDate);
        fields.mandatory(CaseData::getWillHasCodicils);
        fields.mandatory(CaseData::getCodicilAddedDateList)
                    .fieldShowCondition("willHasCodicils=\"Yes\"");
        fields.mandatory(CaseData::getLanguagePreferenceWelsh)
                    .caseEventFieldLabel("Do you need a bilingual grant in English and Welsh?");
        fields.readonly(CaseData::getSolsSolicitorIsExec)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
    }
}
