package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code deleteForCreation1} of event {@code solicitorDeleteApplicationCreation}.
 */
public final class SolicitorDeleteApplicationCreationDeleteForCreation1Page {
    private SolicitorDeleteApplicationCreationDeleteForCreation1Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("deleteForCreation1");
        fields.readonlyNoSummary(CaseData::getDeleteApplication);
    }
}
