package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateApplicationPage2} of event {@code solicitorUpdateApplication}.
 */
public final class SolicitorUpdateApplicationSolicitorUpdateApplicationPage2Page {
    private SolicitorUpdateApplicationSolicitorUpdateApplicationPage2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateApplicationPage2");
        fields.pageLabel("Inheritance Tax");
        fields.mandatory(CaseData::getIhtFormEstateValuesCompleted)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\"")
                    .caseEventFieldLabel("Did you complete Inheritance Tax (IHT) forms to report the estate’s value?");
        fields.mandatory(CaseData::getIhtFormEstate)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getLabelIhtEstate)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\"");
        fields.mandatory(CaseData::getIhtEstateGrossValue)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\"");
        fields.mandatory(CaseData::getIhtEstateNetValue)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\"");
        fields.mandatory(CaseData::getIhtEstateNetQualifyingValue)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"Yes\" AND ihtFormEstateValuesCompleted=\"No\"")
                    .caseEventFieldHint("If the Net qualifying value is Nil, enter 0");
        fields.mandatory(CaseData::getIhtFormId)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"No\"")
                    .caseEventFieldLabel("Which Inheritance Tax (IHT) form was completed?");
        fields.mandatory(CaseData::getIht217)
                    .fieldShowCondition("dateOfDeathAfterEstateSwitch=\"No\" AND ihtFormId=\"IHT205\"")
                    .caseEventFieldLabel("Did you complete the IHT217 to claim 100% unused nil-rate band?");
    }
}
