package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateProbatePage3} of event {@code solicitorUpdateProbate}.
 */
public final class SolicitorUpdateProbateSolicitorUpdateProbatePage3Page {
    private SolicitorUpdateProbateSolicitorUpdateProbatePage3Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateProbatePage3");
        fields.showCondition("dispenseWithNotice=\"Yes\"");
        fields.mandatory(CaseData::getDispenseWithNoticeLeaveGiven);
        fields.mandatory(CaseData::getDispenseWithNoticeLeaveGivenDate)
                    .fieldShowCondition("dispenseWithNoticeLeaveGiven=\"Yes\"");
        fields.mandatory(CaseData::getDispenseWithNoticeOverview)
                    .fieldShowCondition("dispenseWithNoticeLeaveGiven=\"No\"");
        fields.mandatory(CaseData::getDispenseWithNoticeSupportingDocs)
                    .fieldShowCondition("dispenseWithNoticeLeaveGiven=\"No\"");
        fields.mandatory(CaseData::getDispenseWithNoticeOtherExecsList);
    }
}
