package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateIntestacyPage1} of event {@code solicitorUpdateIntestacy}.
 */
public final class SolicitorUpdateIntestacySolicitorUpdateIntestacyPage1Page {
    private SolicitorUpdateIntestacySolicitorUpdateIntestacyPage1Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateIntestacyPage1");
        fields.pageLabel("About the applicant");
        fields.readonlyNoSummary(CaseData::getSolsApplicantNameSection);
        fields.mandatory(CaseData::getPrimaryApplicantForenames);
        fields.mandatory(CaseData::getPrimaryApplicantSurname);
        fields.optional(CaseData::getPrimaryApplicantPhoneNumber);
        fields.mandatory(CaseData::getPrimaryApplicantEmailAddress);
        fields.mandatory(CaseData::getPrimaryApplicantAddress);
        fields.mandatory(CaseData::getLanguagePreferenceWelsh)
                    .caseEventFieldLabel("Do you need a bilingual grant in English and Welsh?");
    }
}
