package uk.gov.hmcts.probate.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.probate.model.ccd.raw.request.CaseData;
import uk.gov.hmcts.probate.model.ccd.raw.request.State;
import uk.gov.hmcts.probate.model.ccd.raw.request.UserRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 *
 * <p>Wizard page {@code solicitorUpdateIntestacyPage2} of event {@code solicitorUpdateIntestacy}.
 */
public final class SolicitorUpdateIntestacySolicitorUpdateIntestacyPage2Page {
    private SolicitorUpdateIntestacySolicitorUpdateIntestacyPage2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("solicitorUpdateIntestacyPage2");
        fields.pageLabel("Applicant and deceased relations");
        fields.mandatory(CaseData::getDeceasedDomicileInEngWales)
                    .fieldShowCondition("[STATE]=\"NeverShow\"")
                    .retainHiddenValue();
        fields.readonlyNoSummary(CaseData::getSolsApplicantRelationshipSection);
        fields.mandatory(CaseData::getSolsApplicantRelationshipToDeceased);
        fields.mandatory(CaseData::getSolsAdoptedEnglandOrWales)
                    .fieldShowCondition("solsApplicantRelationshipToDeceased=\"ChildAdopted\"");
        fields.mandatory(CaseData::getSolsApplicantSiblings)
                    .fieldShowCondition("solsApplicantRelationshipToDeceased=\"Child*\"");
        fields.readonlyNoSummary(CaseData::getSolsApplicantSiblingsInfo)
                    .fieldShowCondition("solsApplicantRelationshipToDeceased=\"Child*\" AND solsApplicantSiblings=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getSolsDeceasedRelationsSection);
        fields.mandatory(CaseData::getDeceasedMaritalStatus);
        fields.mandatory(CaseData::getSolsSpouseOrCivilRenouncing)
                    .fieldShowCondition("solsApplicantRelationshipToDeceased=\"Child*\" AND deceasedMaritalStatus=\"marriedCivilPartnership\"");
        fields.readonly(CaseData::getSolsSpouseOrCivilRenouncingInfo)
                    .fieldShowCondition("solsSpouseOrCivilRenouncing=\"No\" AND solsApplicantRelationshipToDeceased=\"Child*\"");
        fields.mandatory(CaseData::getSolsMinorityInterest);
        fields.readonly(CaseData::getSolsMinorityInterestInfo)
                    .fieldShowCondition("solsMinorityInterest=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getSolsDeceasedPropertySection)
                    .fieldShowCondition("deceasedDomicileInEngWales=\"No\"");
        fields.mandatory(CaseData::getImmovableEstate)
                    .fieldShowCondition("deceasedDomicileInEngWales=\"No\"");
        fields.readonlyNoSummary(CaseData::getImmovableEstateInfo)
                    .fieldShowCondition("immovableEstate=\"No\"");
    }
}
