package uk.gov.hmcts.probate.model.legacy;

import lombok.Data;

@Data
public class GrantApplication {




//    PROBATE_NUMBER   	varchar(11)	,
//    PROBATE_VERSION 	int	,
//    DECEASED_ID          	bigint,
//    DECEASED_FORENAMES	varchar(50)	,
//    DECEASED_SURNAME	varchar(50)	,
//    DATE_OF_BIRTH	date	,
//    DATE_OF_DEATH1	date	,
//    DECEASED_ADDRESS	varchar(500)	,
//    DECEASED_TEXT	varchar(32000)	,
//    ALIAS_NAMES	varchar(32000)	,
//    GRANT_APPLICATION_TEXT	varchar(32000)	,
//    APPLICATION_EVENT_TEXT	varchar(32000)	,
//    OATH_TEXT 	varchar(32000)	,
//    EXECUTOR_TEXT	varchar(32000)	,
//    OTHER_INFORMATION_TEXT 	varchar(32000)	,
//    LINKED_DECEASED_IDS	varchar(32000)	,
//    CCD_CASE_NO	varchar(20)	,
//    ID	bigint	,
//    DNM_IND	varchar(1)	,
//    DECEASED_AGE_AT_DEATH	int	,
//    DECEASED_DEATH_TYPE	varchar(40)	,
//    DECEASED_DOMICILE	varchar(60)	,
//    DECEASED_DOMICILE_IN_WELSH	varchar(10)	,
//    DECEASED_DOMICILE_WELSH	varchar(60)	,
//    DECEASED_HONOURS	varchar(100)	,
//    DECEASED_SEX	varchar(1)	,
//    DECEASED_TITLE	varchar(35)	,
//    APP_ADMIN_CLAUSE_LIMITATION	varchar(100)	,
//    APP_ADMIN_CLAUSE_LIMITN_WELSH 	varchar(100)	,
//    APP_CASE_TYPE	varchar(20)	,
//    APP_EXECUTOR_LIMITATION 	varchar(100)	,
//    APP_EXECUTOR_LIMITATION_WELSH 	varchar(100)	,
//    APP_RECEIVED_DATE	date	,
//    APPLICANT_ADDRESS 	varchar(500)	,
//    APPLICANT_DX_EXCHANGE 	varchar(25)	,
//    APPLICANT_DX_NUMBER 	varchar(10)	,
//    APPLICANT_FORENAMES 	varchar(50)	,
//    APPLICANT_HONOURS	varchar(100)	,
//    APPLICANT_SURNAME 	varchar(50)	,
//    APPLICANT_TITLE	varchar(35)	,
//    GRANT_WELSH_LANGUAGE_IND 	boolean	,
//    GRANT_WILL_TYPE 	varchar(200)	,
//    GRANT_WILL_TYPE_WELSH	varchar(200)	,
//    EXCEPTED_ESTATE_IND varchar(1),
//    FILESLIP_SIGNAL boolean,
//    GRANT_APPLICANT_TYPE varchar(1),
//    GRANT_CONFIRMED_DATE date,
//    GRANT_ISSUED_DATE date,
//    GRANT_ISSUED_SIGNAL boolean,
//    GRANT_LIMITATION varchar(800),
//    GRANT_LIMITATION_WELSH varchar(800),
//    GRANT_POWER_RESERVED varchar(1),
//    GRANT_SOL_ID varchar(10),
//    GRANT_TYPE varchar(3),
//    GRANT_VERSION_DATE date,
//    GRANTEE1_ADDRESS 	varchar(500)	,
//    GRANTEE1_FORENAMES 	varchar(50)	,
//    GRANTEE1_HONOURS 	varchar(100)	,
//    GRANTEE1_SURNAME 	varchar(50)	,
//    GRANTEE1_TITLE 	varchar(35)	,
//    GRANTEE2_ADDRESS 	varchar(500)	,
//    GRANTEE2_FORENAMES 	varchar(50)	,
//    GRANTEE2_HONOURS 	varchar(100)	,
//    GRANTEE2_SURNAME 	varchar(50)	,
//    GRANTEE2_TITLE 	varchar(35)	,
//    GRANTEE3_ADDRESS 	varchar(500)	,
//    GRANTEE3_FORENAMES 	varchar(50)	,
//    GRANTEE3_HONOURS 	varchar(100)	,
//    GRANTEE3_SURNAME 	varchar(50)	,
//    GRANTEE3_TITLE 	varchar(35)	,
//    GRANTEE4_ADDRESS 	varchar(500)	,
//    GRANTEE4_FORENAMES 	varchar(50)	,
//    GRANTEE4_HONOURS 	varchar(100)	,
//    GRANTEE4_SURNAME 	varchar(50)	,
//    GRANTEE4_TITLE 	varchar(35)	,
//    GROSS_ESTATE_VALUE	bigint	,
//    NET_ESTATE_VALUE 	bigint	,
//    PLACE_OF_ORIGINAL_GRANT 	varchar(60)	,
//    PLACE_OF_ORIGINAL_GRANT_WELSH varchar(60),
//    POWER_RESERVED_WELSH	varchar(1)	,
//    RESEAL_DATE	date	,
//    SOLICITOR_REFERENCE	varchar(30)
//
//
}
