package uk.gov.hmcts.probate.model.ccd.raw.request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class Aliases {
    @CCD(
            label = "Type"
    )
    private String type;

    @CCD(
            label = "Prefix"
    )
    private String prefix;

    @CCD(
            label = "Alias first name(s)"
    )
    private String forenames;

    @CCD(
            label = "Alias last name"
    )
    private String lastName;

    @CCD(
            label = "Suffix"
    )
    private String suffix;
}
