package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "aliasReasonList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum AliasReasonList implements HasLabel {
    MARRIAGE("Marriage or civil partnership", "Marriage"),

    DIVORCE("Divorce or dissolution", "Divorce"),

    CHANGE_BY_DEED_POLL("Change by deed poll", "Change by deed poll"),

    DIFFERENT_SPELLING("Different Spelling", "differentSpelling"),

    PART_OF_NAME_NOT_INCLUDED("Part of their name was not included", "partOfNameNotIncluded"),

    OTHER("Other", "other");

    private final String label;

    @JsonValue
    private final String code;
}
