package uk.gov.hmcts.probate.model.ccd.raw.request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "boCaseStopReason",
        generate = true
)
public class BoCaseStopReason {
    @CCD(
            label = "Select a reason for stopping the case",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "stopReasonFixedList"
    )
    private StopReasonFixedList caseStopReason;

    @CCD(
            label = "Select the document that is required",
            showCondition = "caseStopReason=\"DocumentsRequired\"",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "DocumentsRequiredSubList"
    )
    private DocumentsRequiredSubList caseStopSubReasonDocRequired;
}
