package uk.gov.hmcts.probate.model.ccd.raw.request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "boHandoffReason",
        generate = true
)
public class BoHandoffReason {
    @CCD(
            label = "Select a reason for Handoff",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "handoffReasonFixedList"
    )
    private HandoffReasonFixedList caseHandoffReason;
}
