package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "caseTypeFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum CaseTypeFixedList implements HasLabel {
    GOP("Grant of Probate", "gop"),

    INTESTACY("Intestacy", "intestacy"),

    ADMON_WILL("Admon Will", "admonWill"),

    EDGE_CASE("Edge Case", "edgeCase"),

    AD_COLLIGENDA_BONA("Ad Colligenda Bona", "adColligendaBona");

    private final String label;

    @JsonValue
    private final String code;
}
