package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "categoriesTypes",
        generate = true
)
@Getter
@AllArgsConstructor
public enum CategoriesTypes implements HasLabel {
    FOR_DOM("Category 1 - Foreign Domicile", "ForDom"),

    ENT("Category 2 - Entitlement", "Ent"),

    IHT("Category 3 - IHT", "IHT"),

    INCAP("Category 4 - Incapacity", "Incap"),

    LIFE_MINOR("Category 5 - Life and Minority Interest", "LifeMinor"),

    MISS_INFO("Category 6 – Missing/Further information", "MissInfo"),

    WILL("Category 7 - Will", "Will"),

    SOT("Category 8 - Statement of truth incomplete", "SOT"),

    WITNESS("Category 9 - Witness", "Witness"),

    SOL_GEN("Category 10 - Solicitor General", "SolGen"),

    SOL_CERT("Category 11 - Solicitor Certs", "SolCert"),

    SOL_AFFIDAVIT("Category 12 - Solicitors Affidavit", "SolAffidavit"),

    SOL_REDEC("Category 13 - Solicitors Redeclare", "SolRedec");

    private final String label;

    @JsonValue
    private final String code;
}
