package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "checkYourAnswersEventTransitions",
        generate = true
)
@Getter
@AllArgsConstructor
public enum CheckYourAnswersEventTransitions implements HasLabel {
    SOL_APP_CREATED_SOLICITOR_DTLS("Update Probate practitioner details", "SolAppCreatedSolicitorDtls"),

    SOL_APP_CREATED_DECEASED_DTLS("Update deceased details", "SolAppCreatedDeceasedDtls"),

    SOL_DECEASED_DETAILS("Update will details", "SolDeceasedDetails"),

    SOL_WILL_DETAILS_UPDATED("Update deceased estate details", "SolWillDetailsUpdated"),

    SOL_ESTATE_DETAILS_UPDATED("Update executor details", "SolEstateDetailsUpdated");

    private final String label;

    @JsonValue
    private final String code;
}
