package uk.gov.hmcts.probate.model.ccd.raw.request;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "citizenHubResponse",
        generate = true
)
public class CitizenHubResponse {
    @CCD(
            label = "Citizen's response",
            typeOverride = FieldType.TextArea
    )
    private String citizenResponse;

    @CCD(
            label = "Submitted Date"
    )
    private LocalDateTime submittedDate;
}
