package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "damageTypes",
        generate = true
)
@Getter
@AllArgsConstructor
public enum DamageTypes implements HasLabel {
    STAPLE_OR_PUNCH_HOLES("Staples or punch holes", "stapleOrPunchHoles"),

    RUST_MARKS("Rust marks", "rustMarks"),

    PAPER_CLIP_MARKS("Paper clip marks", "paperClipMarks"),

    TORN_EDGES("Torn edges", "tornEdges"),

    WATER_DAMAGE("Water damage", "waterDamage"),

    OTHER_VISIBLE_DAMAGE("Other", "otherVisibleDamage");

    private final String label;

    @JsonValue
    private final String code;
}
