package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum DocumentsRequiredSubList implements HasLabel {
    AFFIDAVITS("Affidavits", "Affidavits"),

    CAPA5_C("CAP A5C", "CAPA5C"),

    DECREE_ABSOLUTE("Decree Absolute", "DecreeAbsolute"),

    GRANTS("Grants", "Grants"),

    IHT205("IHT 205", "IHT205"),

    IHT207("IHT 207", "IHT207"),

    PA1_A("PA1A", "PA1A"),

    PA1_P("PA1P", "PA1P"),

    PA11("PA11", "PA11"),

    PA12("PA12", "PA12"),

    PA13("PA13", "PA13"),

    PA14("PA14", "PA14"),

    PA15("PA15", "PA15"),

    PA16("PA16", "PA16"),

    PA17("PA17", "PA17"),

    PA19("PA19", "PA19"),

    POWER_OF_ATTORNEY("Power of attorney", "PowerOfAttorney"),

    RENUNCIATION("Renunciation", "Renunciation"),

    RESOLUTIONS("Resolutions", "Resolutions");

    private final String label;

    @JsonValue
    private final String code;
}
