package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "documentUploadTypeEnum",
        generate = true
)
@Getter
@AllArgsConstructor
public enum DocumentUploadTypeEnum implements HasLabel {
    EMAIL("Email", "email"),

    CORRESPONDENCE("Correspondence", "correspondence"),

    WILL("Will", "will"),

    IHT("Codicil", "IHT"),

    UPLOADED_LEGAL_STATEMENT("Uploaded Legal Statement", "uploadedLegalStatement"),

    DEATH_CERTIFICATE("Death Certificate", "deathCertificate"),

    CITIZEN_HUB_UPLOAD("Citizen hub upload", "citizenHubUpload"),

    PA1_FORM("PA1 form", "pa1Form"),

    AFFIDAVITS("Affidavits", "affidavits"),

    WITNESS_QUESTIONNAIRES("Witness questionnaires", "witnessQuestionnaires"),

    OTHER("Other", "other");

    private final String label;

    @JsonValue
    private final String code;
}
