package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "documentUpload",
        generate = true
)
public class DocumentUpload {
    @JsonProperty("DocumentType")
    @CCD(
            label = "Type",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "documentUploadTypeEnum"
    )
    private DocumentUploadTypeEnum documentType;

    @JsonProperty("DocumentLink")
    @CCD(
            label = "Document Url"
    )
    private Document documentLink;

    @JsonProperty("Comment")
    @CCD(
            label = "Comment",
            typeOverride = FieldType.TextArea
    )
    private String comment;
}
