package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum DomiciledDetails implements HasLabel {
    DOMICILED_PERM_E_W("domiciled permanently in England or Wales", "domiciledPermE&W"),

    INTENDED_RETURN_E_W("intending to return to England or Wales to domicile permanently", "intendedReturnE&W"),

    DOMICILED_OUTSIDE_E_W("domiciled outside of England and Wales", "domiciledOutsideE&W");

    private final String label;

    @JsonValue
    private final String code;
}
