package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "entitledToApplyFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum EntitledToApplyFixedList implements HasLabel {
    EXECUTORS("The executor/s named in the will/codicil of the person who has died", "executors"),

    ATTORNERY_EXECUTORS("The Attorney/s acting on behalf of the executor/s named in the will/ codicil of the person who has died ", "attorneryExecutors"),

    BENEFICIARY("Beneficiary/s named in the will/codicil of the person who has died ", "beneficiary"),

    ATTORNEY_BENEFICIARY("The Attorney/s acting on behalf of the beneficiary/s named in the will/ codicil of the person who has died ", "attorneyBeneficiary"),

    OTHER("Other", "other");

    private final String label;

    @JsonValue
    private final String code;
}
