package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum EntParagraphs implements HasLabel {
    ENT_EXEC_NO_ACC("Executor not accounted for", "EntExecNoAcc"),

    ENT_ATTORNEY("Attorney and Executor cannot apply together", "EntAttorney"),

    ENT_LEADING_APP("Leading Grant Application required", "EntLeadingApp"),

    ENT_NO_TITLE("No title", "EntNoTitle"),

    ENT_TWO_APPS("Two applications pending", "EntTwoApps"),

    ENT_FAM_TREE("Family tree", "EntFamTree"),

    ENT_DEATH_PA("Confirm death of 1st named executor", "EntDeathPa"),

    ENT_SUB_EXEC("Substituted executor applying when sole executor survives", "EntSubExec"),

    ENT_PREJUDICED("Prejudiced by proof of will", "EntPrejudiced"),

    ENT_WRONG_EXEC("Wrongly accounted executor", "EntWrongExec");

    private final String label;

    @JsonValue
    private final String code;
}
