package uk.gov.hmcts.probate.model.ccd.raw.request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class ExecutorActingForTrustCorp {
    @CCD(
            label = "First name(s)"
    )
    private String additionalExecForenames;

    @CCD(
            label = "Last name(s)"
    )
    private String additionalExecLastname;

    @CCD(
            label = "Name of their position within the trust corporation as per the resolution"
    )
    private String additionalExecutorTrustCorpPosition;
}
