package uk.gov.hmcts.probate.model.ccd.raw.request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class Fees {
    @CCD(
            label = "Application Fee",
            typeOverride = FieldType.MoneyGBP
    )
    private String applicationFee;

    @CCD(
            label = "Application Fee Code"
    )
    private String applicationFeeCode;

    @CCD(
            label = "Application Fee Version"
    )
    private String applicationFeeVersion;

    @CCD(
            label = "UK copies Fee",
            typeOverride = FieldType.MoneyGBP
    )
    private String ukCopiesFee;

    @CCD(
            label = "UK copies Fee Code"
    )
    private String ukCopiesFeeCode;

    @CCD(
            label = "UK copies Fee Version"
    )
    private String ukCopiesFeeVersion;

    @CCD(
            label = "Overseas copies Fee",
            typeOverride = FieldType.MoneyGBP
    )
    private String overseasCopiesFee;

    @CCD(
            label = "Overseas Fee Code"
    )
    private String overseasCopiesFeeCode;

    @CCD(
            label = "Overseas Fee Version"
    )
    private String overseasCopiesFeeVersion;

    @CCD(
            label = "Total Fees",
            typeOverride = FieldType.MoneyGBP
    )
    private String total;
}
