package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum ForDomParagraphs implements HasLabel {
    FOR_DOM_INITIAL("Initial Enquiry", "ForDomInitial"),

    FOR_DOM_AFFIDAVIT("Affidavit of Law", "ForDomAffidavit");

    private final String label;

    @JsonValue
    private final String code;
}
