package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "handoffReasonFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum HandoffReasonFixedList implements HasLabel {
    COLLIGENDA_BONA("Ad Colligenda Bona", "ColligendaBona"),

    FOREIGN_WILL("Application to prove a foreign will", "ForeignWill"),

    RECTIFY_WILL_CODICIL("Application to rectify a will or codicil", "RectifyWillCodicil"),

    CODICIL_MIS("Codicil mis-recital", "CodicilMis"),

    DE_BONIS_NON("De Bonis Non", "DeBonisNon"),

    DOUBLE_PROBATE("Double Probate", "DoubleProbate"),

    FIAT_WILL("Fiat Will", "FiatWill"),

    FOREIGN_DOMICILE("Foreign Domicile", "ForeignDomicile"),

    HORIZON_SCHEME("Horizon Scheme", "HorizonScheme"),

    IBCA("Infected Blood Compensation Authority (IBCA)", "IBCA"),

    IBIS("Infected Blood Interim Scheme", "IBIS"),

    INCAPACITY_RULE35("Incapacity under rule 35", "IncapacityRule35"),

    LEADING_FOLLOWING_GRANTS("Leading / following Grants", "LeadingFollowing Grants"),

    LITERARY_ESTATE("Literary Estate", "LiteraryEstate"),

    LOST_WILL("Lost Will / Codicil", "LostWill"),

    MINORITY_INTEREST("Minority Interest", "MinorityInterest"),

    POA("Power of Attorney (POA)", "POA"),

    RESEAL_FOREIGN_GRANT("Reseal of Foreign Grant", "ResealForeignGrant"),

    SECTION116("Section 116 (Order to bypass prior entitlement)", "Section116"),

    SPREADSHEET("Spreadsheet", "Spreadsheet"),

    TRUST_CORPORATION("Trust Corporation", "TrustCorporation"),

    WILL_CODICIL_NOTATED("Will or codicil to be notated", "WillCodicilNotated"),

    WINDRUSH_SCHEME("Windrush Scheme", "WindrushScheme"),

    WITNESS_INTERVIEW("Witness Interview", "WitnessInterview");

    private final String label;

    @JsonValue
    private final String code;
}
