package uk.gov.hmcts.probate.model.ccd.raw.request;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum IHTFormID implements HasLabel {
    IHT400("IHT400"),

    IHT205("IHT205"),

    IHT207("IHT207"),

    IHT400421("IHT 400 and IHT421 - submitted before 17 January 2024"),

    NA("Not applicable");

    private final String label;
}
