package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum IHTParagraphs implements HasLabel {
    IHT205_MISS("IHT205 Missing", "IHT205Miss"),

    IHT421_AWAIT("Awaiting IHT421", "IHT421Await"),

    IHT205_NO_ASSETS("No assets on IHT205", "IHT205NoAssets"),

    IHT205_GROSS_ESTATE_OVER("Gross estate over £325,000(IHT205)", "IHT205GrossEstateOver"),

    IHT217_MISS("IHT217 missing", "IHT217Miss"),

    IHT400("IHT400", "IHT400");

    private final String label;

    @JsonValue
    private final String code;
}
