package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum LifeAndMinParagraphs implements HasLabel {
    LMINT_LIFE_AND_MIN("Intestacy: Life and Minority interest", "LMIntLifeAndMin"),

    LMINT_LIFE("Intestacy: Life interest", "LMIntLife"),

    LMINT_MINOR("Intestacy: Minority interest", "LMIntMinor"),

    LMADMON_LIFE("Admon Will: Life interest", "LMAdmonLife"),

    LMADMON_MINOR("Admon Will: Minority interest", "LMAdmonMinor"),

    LMINT_PARENTAL("Intestacy: Minority interest parental responsibility", "LMIntParental");

    private final String label;

    @JsonValue
    private final String code;
}
