package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "martialStatusFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum MartialStatusFixedList implements HasLabel {
    MARRIED_CIVIL_PARTNERSHIP("Married or in a civil partnership", "marriedCivilPartnership"),

    DIVORCED_CIVIL_PARTNERSHIP("Divorced or civil partnership has dissolved", "divorcedCivilPartnership"),

    WIDOWED("Widowed, their spouse or civil partner died before them", "widowed"),

    JUDICIALLY("Judicially separated", "judicially"),

    NEVER_MARRIED("Never married", "neverMarried");

    private final String label;

    @JsonValue
    private final String code;
}
