package uk.gov.hmcts.probate.model.ccd.raw.request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class ModifiedOCRField {
    @CCD(
            label = "OCR Field"
    )
    private String fieldName;

    @CCD(
            label = "Original Value"
    )
    private String originalValue;
}
