package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "notApplyingExecutorReasonFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum NotApplyingExecutorReasonFixedList implements HasLabel {
    DIED_BEFORE("They died before the deceased", "DiedBefore"),

    DIED_AFTER("They died after the deceased", "DiedAfter"),

    POWER_RESERVED("They're holding power reserved", "PowerReserved"),

    RENUNCIATION("They have renounced", "Renunciation"),

    POWER_OF_ATTORNEY("They have appointed or wish to appoint another person to act as their attorney", "PowerOfAttorney"),

    MENTALLY_INCAPABLE("They lack capacity to act as executor and the will allows for a substitution", "MentallyIncapable");

    private final String label;

    @JsonValue
    private final String code;
}
