package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "paperPaymentMethodFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PaperPaymentMethodFixedList implements HasLabel {
    DEBIT_OR_CREDIT("Debit or Credit card", "debitOrCredit"),

    CHEQUE("Cheque or Postal order", "cheque"),

    CASH("Cash", "cash"),

    FEE_ACCOUNT("Fee account", "feeAccount");

    private final String label;

    @JsonValue
    private final String code;
}
