package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "paymentMethodEnum",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PaymentMethodEnum implements HasLabel {
    CHEQUE("Cheque", "cheque"),

    ONLINE("Online", "online"),

    CARD("Credit/debit card", "card"),

    PBA("PBA Account", "pba");

    private final String label;

    @JsonValue
    private final String code;
}
