package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "paymentStatusEnum",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PaymentStatusEnum implements HasLabel {
    SUCCESS("Success", "Success"),

    INITIATED("Initiated", "Initiated"),

    FAILED("Failed", "Failed"),

    PENDING("Pending", "Pending"),

    NOT_REQUIRED("Not Required", "not_required");

    private final String label;

    @JsonValue
    private final String code;
}
