package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "probateDocumentTypeEnum",
        generate = true
)
@Getter
@AllArgsConstructor
public enum ProbateDocumentTypeEnum implements HasLabel {
    DIGITAL_GRANT("Digital Grant", "digitalGrant"),

    DIGITAL_GRANT_DRAFT("Digital Grant Draft", "digitalGrantDraft"),

    LEGAL_STATEMENT("Legal Statement", "legalStatement"),

    LEGAL_STATEMENT_ADMON("Legal Statement", "legalStatementAdmon"),

    LEGAL_STATEMENT_PROBATE("Legal Statement", "legalStatementProbate"),

    LEGAL_STATEMENT_GRANT_OF_PROBATE("Legal Statement", "legalStatementGrantOfProbate"),

    LEGAL_STATEMENT_INTESTACY("Legal Statement", "legalStatementIntestacy"),

    SENT_EMAIL("Sent Email", "sentEmail"),

    INTESTACY_GRANT("Intestacy Grant", "intestacyGrant"),

    INTESTACY_GRANT_DRAFT("Intestacy Grant Draft", "intestacyGrantDraft"),

    ADMON_WILL_GRANT("Admon Will Grant", "admonWillGrant"),

    ADMON_WILL_GRANT_DRAFT("Admon Will Grant Draft", "admonWillGrantDraft"),

    AD_COLLIGENDA_BONA_GRANT("Ad Colligenda Bona Grant", "adColligendaBonaGrant"),

    AD_COLLIGENDA_BONA_GRANT_DRAFT("Ad Colligenda Bona Grant Draft", "adColligendaBonaGrantDraft"),

    CAVEAT_STOPPED("caveat Stopped", "caveatStopped"),

    GRANT_COVERSHEET("Cover Sheet", "grantCoversheet"),

    GRANT_COVER("Grant Cover Sheet", "grantCover"),

    GRANT_RAISED("Grant Raised", "grantRaised"),

    DIGITAL_GRANT_REISSUE_DRAFT("Digital Grant Reissue Draft", "digitalGrantReissueDraft"),

    INTESTACY_GRANT_REISSUE_DRAFT("Intestacy Grant Reissue Draft", "intestacyGrantReissueDraft"),

    ADMON_WILL_GRANT_REISSUE_DRAFT("Admon Will Grant Reissue Draft", "admonWillGrantReissueDraft"),

    AD_COLLIGENDA_BONA_GRANT_REISSUE_DRAFT("Ad Colligenda Bona Grant Reissue Draft", "adColligendaBonaGrantReissueDraft"),

    DIGITAL_GRANT_REISSUE("Digital Grant Reissue", "digitalGrantReissue"),

    INTESTACY_GRANT_REISSUE("Intestacy Grant Reissue", "intestacyGrantReissue"),

    ADMON_WILL_GRANT_REISSUE("Admon Will Grant Reissue", "admonWillGrantReissue"),

    AD_COLLIGENDA_BONA_GRANT_REISSUE("Ad Colligenda Bona Grant Reissue", "adColligendaBonaGrantReissue"),

    DORMANT_REMINDER("Dormant Reminder", "dormantReminder"),

    WELSH_DIGITAL_GRANT("Welsh Digital Grant", "welshDigitalGrant"),

    WELSH_DIGITAL_GRANT_DRAFT("Welsh Digital Grant Draft", "welshDigitalGrantDraft"),

    WELSH_INTESTACY_GRANT("Welsh Intestacy Grant", "welshIntestacyGrant"),

    WELSH_INTESTACY_GRANT_DRAFT("Welsh Intestacy Grant Draft", "welshIntestacyGrantDraft"),

    WELSH_ADMON_WILL_GRANT("Welsh Admon Will Grant", "welshAdmonWillGrant"),

    WELSH_ADMON_WILL_GRANT_DRAFT("Welsh Admon Will Grant Draft", "welshAdmonWillGrantDraft"),

    WELSH_AD_COLLIGENDA_BONA_GRANT("Welsh Ad Colligenda Bona Grant", "welshAdColligendaBonaGrant"),

    WELSH_AD_COLLIGENDA_BONA_GRANT_DRAFT("Welsh Ad Colligenda Bona Grant Draft", "welshAdColligendaBonaGrantDraft"),

    WELSH_DIGITAL_GRANT_REISSUE_DRAFT("Welsh Digital Grant Reissue Draft", "welshDigitalGrantReissueDraft"),

    WELSH_INTESTACY_GRANT_REISSUE_DRAFT("Welsh Intestacy Grant Reissue Draft", "welshIntestacyGrantReissueDraft"),

    WELSH_ADMON_WILL_GRANT_REISSUE_DRAFT("Welsh Admon Will Grant Reissue Draft", "welshAdmonWillGrantReissueDraft"),

    WELSH_AD_COLLIGENDA_BONA_GRANT_REISSUE_DRAFT("Welsh Ad Colligenda Bona Grant Reissue Draft", "welshAdColligendaBonaGrantReissueDraft"),

    WELSH_DIGITAL_GRANT_REISSUE("Welsh Digital Grant Reissue", "welshDigitalGrantReissue"),

    WELSH_INTESTACY_GRANT_REISSUE("Welsh Intestacy Grant Reissue", "welshIntestacyGrantReissue"),

    WELSH_ADMON_WILL_GRANT_REISSUE("Welsh Admon Will Grant Reissue", "welshAdmonWillGrantReissue"),

    WELSH_AD_COLLIGENDA_BONA_GRANT_REISSUE("Welsh Ad Colligenda Bona Grant Reissue", "welshAdColligendaBonaGrantReissue"),

    SOT_INFORMATION_REQUEST("Legal Statement Information Request", "sotInformationRequest"),

    STATEMENT_OF_TRUTH("Legal Statement", "statementOfTruth"),

    WELSH_STATEMENT_OF_TRUTH("Legal Statement", "welshStatementOfTruth"),

    ASSEMBLED_LETTER("Assembled Letter", "assembledLetter"),

    BLANK_LETTER("Blank Letter", "blankLetter"),

    OTHER("Other", "other"),

    WELSH_DORMANT_REMINDER("Welsh Dormant Reminder", "welshDormantReminder");

    private final String label;

    @JsonValue
    private final String code;
}
