package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class ProbateDocument {
    @JsonProperty("DocumentType")
    @CCD(
            label = "Type",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "probateDocumentTypeEnum"
    )
    private ProbateDocumentTypeEnum documentType;

    @JsonProperty("DocumentLink")
    @CCD(
            label = "Document Url"
    )
    private Document documentLink;

    @JsonProperty("DocumentDateAdded")
    @CCD(
            label = "Date added"
    )
    private LocalDate documentDateAdded;

    @JsonProperty("DocumentFileName")
    @CCD(
            label = "File name"
    )
    private String documentFileName;

    @JsonProperty("DocumentGeneratedBy")
    @CCD(
            label = "Generated by"
    )
    private String documentGeneratedBy;
}
