package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "registrarsDecisionType",
        generate = true
)
@Getter
@AllArgsConstructor
public enum RegistrarsDecisionType implements HasLabel {
    PROBATE_REFUSED("Probate refused", "probateRefused"),

    LOST_WILL("Rule 54 (lost will)", "lostWill"),

    OTHER_ORDER("Other order / direction", "otherOrder"),

    REFUSAL("Refusal", "refusal");

    private final String label;

    @JsonValue
    private final String code;
}
