package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "registryLocations",
        generate = true
)
@Getter
@AllArgsConstructor
public enum RegistryLocations implements HasLabel {
    OXFORD("Oxford", "Oxford"),

    BIRMINGHAM("Birmingham", "Birmingham"),

    MANCHESTER("Manchester", "Manchester"),

    LEEDS("Leeds", "Leeds"),

    LIVERPOOL("Liverpool", "Liverpool"),

    BRIGHTON("Brighton", "Brighton"),

    LONDON("London", "London"),

    CARDIFF("Cardiff", "Cardiff"),

    NEWCASTLE("Newcastle", "Newcastle"),

    WINCHESTER("Winchester", "Winchester"),

    CTSC("CTSC", "ctsc"),

    BRISTOL("Bristol", "Bristol");

    private final String label;

    @JsonValue
    private final String code;
}
