package uk.gov.hmcts.probate.model.ccd.raw.request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class ReissueExamineCase {
    @CCD(
            label = "Select a reason for reissuing the case",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "reissueReasonFixedList"
    )
    private ReissueReasonFixedList reissueReason;

    @CCD(
            label = "Describe the details of the reason",
            typeOverride = FieldType.TextArea
    )
    private String reissueReasonDetails;
}
