package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "reissueSelectionFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum ReissueSelectionFixedList implements HasLabel {
    DECEASED_IHT("Deceased, IHT and Estate Details", "deceasedIHT"),

    APPLICANT("Applicant Details", "applicant"),

    GRANT("Grant Details", "grant"),

    DOMICILITY("Domicility and Assets", "domicility"),

    ATTORNEY("Attorney Info", "attorney"),

    WILL_AND_CODICILS("Will and codicils", "willAndCodicils"),

    SOLICITOR("Probate practitioner details", "solicitor"),

    DECEASED_FAMILY("Deceased Family Details", "deceasedFamily"),

    REISSUE_DETAILS("Reissue details", "reissueDetails");

    private final String label;

    @JsonValue
    private final String code;
}
