package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "reissueNotationFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum ReissueNotationFixedList implements HasLabel {
    DUPLICATE("Duplicate of original created on [date of creation]", "duplicate"),

    REGISTRARS_ORDER("Amended and re-issued pursuant to Registrar's order dated [date of order]", "registrarsOrder"),

    REGISTRARS_DIRECTION("Amended and re-issued [date of re-issue] pursuant to Registrar's Direction 004/17", "registrarsDirection");

    private final String label;

    @JsonValue
    private final String code;
}
