package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "relationshipToDeceasedFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum RelationshipToDeceasedFixedList implements HasLabel {
    PARTNER("Spouse", "partner"),

    CHILD("Child", "child"),

    SIBLING("Sibling", "sibling"),

    PARENT("Parent", "parent"),

    OTHER("Other", "other"),

    ADOPTED_CHILD("Adopted child", "adoptedChild");

    private final String label;

    @JsonValue
    private final String code;
}
