package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "resolveStopStateFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum ResolveStopStateFixedList implements HasLabel {
    CASE_PRINTED("Awaiting documentation", "CasePrinted"),

    BOREADY_TO_ISSUE("Ready to issue", "BOReadyToIssue"),

    BOCASE_QA("Case selected for QA", "BOCaseQA");

    private final String label;

    @JsonValue
    private final String code;
}
