package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "resolveEscalationStateFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum ResolveEscalationStateFixedList implements HasLabel {
    CASE_PRINTED("Awaiting documentation", "CasePrinted"),

    BOCASE_STOPPED_AWAIT_REDEC("Awaiting redeclaration", "BOCaseStoppedAwaitRedec"),

    BOCASE_CLOSED("Case closed", "BOCaseClosed"),

    BOREADY_TO_ISSUE("Ready to issue", "BOReadyToIssue"),

    BOCASE_QA("Case selected for QA", "BOCaseQA"),

    BOCASE_STOPPED("Case stopped", "BOCaseStopped"),

    BOCAVEAT_PERMENANT("Caveat stop", "BOCaveatPermenant"),

    BOREGISTRAR_ESCALATION("Registrar escalation", "BORegistrarEscalation");

    private final String label;

    @JsonValue
    private final String code;
}
