package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum ScannedDocumentType implements HasLabel {
    COVERSHEET("Coversheet", "coversheet"),

    FORM("Form", "form"),

    WILL("Will", "will"),

    FORENSIC_SHEETS("Forensic Sheet", "forensic_sheets"),

    SUPPORTING_DOCUMENTS("Supporting documents", "supporting_documents"),

    IHT("IHT", "iht"),

    PPS_LEGAL_STATEMENT("PP's Legal statement", "pps_legal_statement"),

    CHERISHED("Cherished", "cherished"),

    OTHER("Other", "other");

    private final String label;

    @JsonValue
    private final String code;
}
