package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum SharingInProfits implements HasLabel {
    PARTNER("Partners", "partner"),

    MEMBER("Members", "member"),

    STAKEHOLDER("Stakeholders", "stakeholder"),

    DIRECTOR("Directors", "director");

    private final String label;

    @JsonValue
    private final String code;
}
