package uk.gov.hmcts.probate.model.ccd.raw.request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.AddressUK;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "solAdditionalExecutor",
        generate = true
)
public class SolAdditionalExecutor {
    @CCD(
            label = "First name(s)"
    )
    private String additionalExecForenames;

    @CCD(
            label = "Last name(s)"
    )
    private String additionalExecLastname;

    @CCD(
            label = "Is this name different to how they are named in the will?"
    )
    private YesOrNo additionalExecNameOnWill;

    @CCD(
            label = "Enter their full name as it appears in the will",
            showCondition = "additionalExecNameOnWill=\"Yes\""
    )
    private String additionalExecAliasNameOnWill;

    @CCD(
            label = "Are they applying?"
    )
    private YesOrNo additionalApplying;

    @CCD(
            label = "Executor address",
            showCondition = "additionalApplying=\"Yes\""
    )
    private AddressUK additionalExecAddress;

    @CCD(
            label = "Why are they not applying?",
            showCondition = "additionalApplying=\"No\""
    )
    private NotApplyingExecutorReasonFixedList additionalExecReasonNotApplying;
}
