package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "solsNotApplyingReasonFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum SolsNotApplyingReasonFixedList implements HasLabel {
    RENUNCIATION("They have renounced", "Renunciation"),

    POWER_RESERVED("They're holding power reserved", "PowerReserved");

    private final String label;

    @JsonValue
    private final String code;
}
