package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum SolsGenParagraphs implements HasLabel {
    GEN_AUTH_PARTNERS("Sol: Renunciation does not cover authority partners", "GenAuthPartners"),

    GEN_EXTEND_RENUNCIATION("Sol: Extended renunciation", "GenExtendRenunciation"),

    GEN_POWER_OF_ATTORNEY("Power of attorney signed abroad", "GenPowerOfAttorney"),

    GEN_UNCERTAINTY("Void for uncertainty", "GenUncertainty");

    private final String label;

    @JsonValue
    private final String code;
}
