package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "solsRelationshipsToDeceased",
        generate = true
)
@Getter
@AllArgsConstructor
public enum SolsRelationshipsToDeceased implements HasLabel {
    SPOUSE_OR_CIVIL("Spouse or civil partner", "SpouseOrCivil"),

    CHILD("Child", "Child"),

    CHILD_ADOPTED("Adopted child", "ChildAdopted");

    private final String label;

    @JsonValue
    private final String code;
}
