package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum SotParagraphs implements HasLabel {
    SOT_PA1P_REDEC("PA1P: Part B - Full redec of application", "SotPa1pRedec"),

    SOT_PA1A_REDEC("PA1A: Part B - Full redec of application", "SotPa1aRedec"),

    SOT_NOT_SIGNED("Paper: Statement of truth not signed", "SotNotSigned"),

    SOT_PA1P_Q2("PA1P Q2 incomplete/wrong", "SotPa1pQ2"),

    SOT_PA1P_Q3("PA1P Q3 incomplete/wrong", "SotPa1pQ3"),

    SOT_PA1P_Q4("PA1P Q4 incomplete/wrong", "SotPa1pQ4"),

    SOT_PA1P_Q5("PA1P Q5 incomplete/wrong", "SotPa1pQ5"),

    SOT_PA1P_Q6("PA1P Q6 incomplete/wrong", "SotPa1pQ6"),

    SOT_PA1P_Q7("PA1P Q7 incomplete/wrong", "SotPa1pQ7"),

    SOT_PA1A_Q2("PA1A Q2 incomplete/wrong", "SotPa1aQ2"),

    SOT_PA1A_Q3("PA1A Q3 incomplete/wrong", "SotPa1aQ3"),

    SOT_PA1A_Q4("PA1A Q4 incomplete/wrong", "SotPa1aQ4"),

    SOT_PA1A_Q5("PA1A Q5 incomplete/wrong", "SotPa1aQ5"),

    SOT_PA1A_Q6("PA1A Q6 incomplete/wrong", "SotPa1aQ6");

    private final String label;

    @JsonValue
    private final String code;
}
