package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum SOTReview1 implements HasLabel {
    BELIEVE_TRUE(" believe(s) that the facts stated in this legal statement are true.", "BelieveTrue");

    private final String label;

    @JsonValue
    private final String code;
}
