package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "spouseNotApplyingReasonFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum SpouseNotApplyingReasonFixedList implements HasLabel {
    RENUNCIATED("Renounced", "renunciated"),

    MENTALLY_INCAPABLE("Mentally incapable", "mentallyIncapable"),

    OTHER("Other", "other");

    private final String label;

    @JsonValue
    private final String code;
}
