package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "stopReasonFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum StopReasonFixedList implements HasLabel {
    DECEASED_ADDRESS_MISSING("Address of deceased missing", "DeceasedAddressMissing"),

    AFFIDAVIT("Affidavit", "Affidavit"),

    ANY_OTHER_WILLS("Any other wills", "AnyOtherWills"),

    APPLICANT_NAME_ISSUE("Applicant Name (missing, spelling etc)", "ApplicantNameIssue"),

    AWAITING_UNIQUE_IHTCODE("Awaiting unique probate IHT code", "AwaitingUniqueIHTCode"),

    CAVEAT_MATCH("Caveat match", "CaveatMatch"),

    DATES_DIFFER("Dates differ (will, Birth, Death)", "DatesDiffer"),

    DEATH_CERT_ISSUE("Death Cert (missing, not original, unreadable)", "DeathCertIssue"),

    DECEASED_NAME("Deceased Name", "DeceasedName"),

    DOCUMENTS_REQUIRED("Documents required", "DocumentsRequired"),

    DUPLICATE_EMAIL_ADDRESSES("Duplicate email addresses", "DuplicateEmailAddresses"),

    EXEC_NOT_ACCOUNTED_FOR("Executor not accounted for", "ExecNotAccountedFor"),

    FEE("Fee", "Fee"),

    FOREIGN_DOMICILE("Foreign Domicile", "ForeignDomicile"),

    IHT421_AWAITING("IHT 421 awaiting", "IHT421Awaiting"),

    IHTFIGURES_INCORRECT("IHT figures incorrect", "IHTFiguresIncorrect"),

    IHTISSUE("IHT forms not received", "IHTIssue"),

    INTESTACY_MINORITY_INTEREST("Intestacy Minority Interest", "IntestacyMinorityInterest"),

    LOST_WILL("Lost Will", "LostWill"),

    MATCHING_APPLICATION("Matching application – (informing Sol or citizen that there is a matching application so their case cannot proceed)", "MatchingApplication"),

    NO_MINORITY_LIFE("No minority or life interest – we ask solicitors to certify this if missing on the Legal Statement", "NoMinorityLife"),

    NOT_ELIGIBLE("Not eligible for digital process", "NotEligible"),

    NOT_ENTITLED("Not entitled to make application", "NotEntitled"),

    ORIGINAL_DOCS_REQUIRED("Original Docs required", "OriginalDocsRequired"),

    WILL_NOT_ENCLOSED("Original will not enclosed", "WillNotEnclosed"),

    PERMANENT_CAVEAT("Permanent Caveat", "Permanent Caveat"),

    PROBATE_FIGURES_INCORRECT("Probate figures incorrect", "ProbateFiguresIncorrect"),

    REDECLARE_TITLE_CLEARING("Re-declare Legal Statement due to Title/Clearing – this would only be on Solicitor applications", "RedeclareTitleClearing"),

    SOLICITORS_LEGAL_STATEMENT_NOT_SIGNED("Solicitors Legal Statement Not Signed", "SolicitorsLegalStatementNotSigned"),

    TRUST_CORP("Trust Corp", "TrustCorp"),

    WILL_CONDITION("Will (condition)", "WillCondition"),

    WILL_CONTENT("Will (content, inc not signed)", "WillContent"),

    WELSH_TRANSLATION_REQUIRED("Welsh Translation Required", "WelshTranslationRequired"),

    OTHER("*** NOT TO BE USED (Other) ***", "Other");

    private final String label;

    @JsonValue
    private final String code;
}
