package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@ComplexType(
        name = "transferToStateFixedList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum TransferToStateFixedList implements HasLabel {
    CASE_PRINTED("Awaiting documentation", "CasePrinted"),

    BOCASE_STOPPED_AWAIT_REDEC("Awaiting redeclaration", "BOCaseStoppedAwaitRedec"),

    BOCASE_CLOSED("Case closed", "BOCaseClosed"),

    BOCASE_IMPORTED("Case imported", "BOCaseImported"),

    BOCASE_MATCHING_ISSUE_GRANT("Case Matching (Issue grant)", "BOCaseMatchingIssueGrant"),

    BOCASE_MATCHING_REISSUE("Case Matching (Reissue grant)", "BOCaseMatchingReissue"),

    CASE_PAYMENT_FAILED("Case payment failed", "CasePaymentFailed"),

    BOCASE_QA("Case selected for QA", "BOCaseQA"),

    BOCASE_STOPPED("Case stopped", "BOCaseStopped"),

    BOCASE_STOPPED_REISSUE("Case stopped (reissue)", "BOCaseStoppedReissue"),

    BOCAVEAT_PERMENANT("Caveat stop", "BOCaveatPermenant"),

    BOEXAMINING_REISSUE("Examining (reissue)", "BOExaminingReissue"),

    BOGRANT_ISSUED("Grant issue", "BOGrantIssued"),

    BOSOT_GENERATED("Legal Statement Generated", "BOSotGenerated"),

    PAAPP_CREATED("PA application created", "PAAppCreated"),

    BOREADY_TO_ISSUE("Ready to issue", "BOReadyToIssue"),

    BOREDEC_NOTIFICATION_SENT("Redeclaration notifications sent", "BORedecNotificationSent"),

    BOREGISTRAR_ESCALATION("Registrar escalation", "BORegistrarEscalation");

    private final String label;

    @JsonValue
    private final String code;
}
