package uk.gov.hmcts.probate.model.ccd.raw.request;

import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.HasRole;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum UserRole implements HasRole {
    GS_PROFILE("GS_profile", "R"),

    CASEWORKER_CAA("caseworker-caa", ""),

    CASEWORKER_APPROVER("caseworker-approver", ""),

    CASEWORKER_PROBATE("caseworker-probate", ""),

    CASEWORKER_PROBATE_ISSUER("caseworker-probate-issuer", ""),

    CASEWORKER_PROBATE_SOLICITOR("caseworker-probate-solicitor", ""),

    CASEWORKER_PROBATE_SYSTEMUPDATE("caseworker-probate-systemupdate", ""),

    CASEWORKER_PROBATE_SCHEDULER("caseworker-probate-scheduler", ""),

    CITIZEN("citizen", ""),

    CASEWORKER_PROBATE_CASEADMIN("caseworker-probate-caseadmin", ""),

    CASEWORKER_PROBATE_CASEOFFICER("caseworker-probate-caseofficer", ""),

    CASEWORKER_PROBATE_REGISTRAR("caseworker-probate-registrar", ""),

    CASEWORKER_PROBATE_SUPERUSER("caseworker-probate-superuser", ""),

    CASEWORKER_PROBATE_PCQEXTRACTOR("caseworker-probate-pcqextractor", ""),

    CASEWORKER_PROBATE_CHARITY("caseworker-probate-charity", ""),

    CASEWORKER_PROBATE_RPAROBOT("caseworker-probate-rparobot", ""),

    TTL_PROFILE("TTL_profile", ""),

    CASEWORKER_WA_TASK_CONFIGURATION("caseworker-wa-task-configuration", ""),

    @CCD(
            label = "Applicant Solicitor",
            hint = "Applicant Solicitor"
    )
    APPLICANTSOLICITOR("[APPLICANTSOLICITOR]", ""),

    @CCD(
            label = "Creator of case",
            hint = "Role specified by CCD"
    )
    CREATOR("[CREATOR]", "");

    private final String role;

    private final String caseTypePermissions;
}
