package uk.gov.hmcts.probate.model.ccd.raw.request;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from GrantOfRepresentation on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum WillParagraphs implements HasLabel {
    WILL_ANY_OTHER("Any other wills", "WillAnyOther"),

    WILL_PLIGHT("Plight and condition of will", "WillPlight"),

    WILL_SEP_PAGES("Separate pages of will", "WillSepPages"),

    WILL_STAPLE("Staple removed for photocopying", "WillStaple"),

    WILL_REVOKED("Will revoked by marriage", "WillRevoked"),

    WILL_LOST("Lost will", "WillLost"),

    WILL_LIST("List/Memo named in will", "WillList"),

    WILL_FIAT("FIAT will Legal Statement", "WillFiat");

    private final String label;

    @JsonValue
    private final String code;
}
